/* =============================================================================
   THE PUZZLE BANK — a month of hard 6x6 Bible crosswords, one for each day.
   -----------------------------------------------------------------------------
   GENERATED FILE. Do not hand-edit: run

     node scripts/build-crossword-puzzles.mjs

   Each puzzle is stored as its solved grid — '#' is a blocked cell, every other
   character is the answer letter that belongs there. js/engine.js derives the
   blocks, the numbering and the across/down entries from this, and looks every
   entry up in js/answers.js for its clue, hint, Scripture reference and
   explanation. That is why a puzzle carries no clue text of its own: there is
   exactly one place a Bible fact can enter this game.

   Answers of four letters and up appear in exactly one puzzle. Three-letter
   answers may serve twice — a grid this small needs connecting tissue, and
   Scripture only offers so many defensible three-letter words.
   ========================================================================== */

export const PUZZLES = [
  {
    id: 'flcc-hard-001',
    category: 'Lesser-Known People',
    difficulty: 'Hard',
    grid: [
      '#RHODA',
      'H##D#B',
      'E#SEED',
      'GOAD#O',
      'A#L##N',
      'ITTAI#',
    ],
  },
  {
    id: 'flcc-hard-002',
    category: 'Kings & Kingdoms',
    difficulty: 'Hard',
    grid: [
      '#PEKAH',
      'J#L##I',
      'AGAG#R',
      'B#MARA',
      'I##T#M',
      'NECHO#',
    ],
  },
  {
    id: 'flcc-hard-003',
    category: 'Bible Geography',
    difficulty: 'Hard',
    grid: [
      'HOREB#',
      'A##Z#A',
      'ZOAR#R',
      'O#NAIN',
      'R#A##O',
      '#EKRON',
    ],
  },
  {
    id: 'flcc-hard-004',
    category: 'Prophets',
    difficulty: 'Hard',
    grid: [
      'AMOS#V',
      'G##E#I',
      'ANNA#S',
      'B#ELOI',
      'U#B##O',
      'S#ONAN',
    ],
  },
  {
    id: 'flcc-hard-005',
    category: 'Women of the Bible',
    difficulty: 'Hard',
    grid: [
      '#ORPAH',
      'I##U##',
      'R#JAEL',
      'ADAH#U',
      '##I##Z',
      'MERAB#',
    ],
  },
  {
    id: 'flcc-hard-006',
    category: 'Objects & Symbols',
    difficulty: 'Hard',
    grid: [
      '#CUBIT',
      'D##E##',
      'EPHA#E',
      'W#OMER',
      '##R##I',
      'BONES#',
    ],
  },
  {
    id: 'flcc-hard-007',
    category: 'Places & Cities',
    difficulty: 'Hard',
    grid: [
      '#MALTA',
      'H#D###',
      'A#ARBA',
      'MYRA#X',
      '###C#E',
      'GERAR#',
    ],
  },
  {
    id: 'flcc-hard-008',
    category: 'New Testament',
    difficulty: 'Hard',
    grid: [
      '#SOWER',
      'A#D###',
      'SEED#A',
      'A#DOOR',
      '###V#D',
      'CAMEL#',
    ],
  },
  {
    id: 'flcc-hard-009',
    category: 'Words of Jesus',
    difficulty: 'Hard',
    grid: [
      '#EWE#L',
      '###B#O',
      'MINA#I',
      'I#ALMS',
      'T#R###',
      'E#DAN#',
    ],
  },
  {
    id: 'flcc-hard-010',
    category: 'Old Testament',
    difficulty: 'Hard',
    grid: [
      '#REU#T',
      '##T##O',
      'AGAG#L',
      'B#MARA',
      'I##T##',
      'B#NER#',
    ],
  },
  {
    id: 'flcc-hard-011',
    category: 'Bible History',
    difficulty: 'Hard',
    grid: [
      '#ELON#',
      '###N#O',
      'SUSA#A',
      'I#ANAK',
      'N#U###',
      '#ELUL#',
    ],
  },
  {
    id: 'flcc-hard-012',
    category: 'Holy Spirit',
    difficulty: 'Hard',
    grid: [
      'AMASAI',
      'W##E##',
      'L#WAY#',
      '#OIL#H',
      '##N##E',
      'GIDEON',
    ],
  },
  {
    id: 'flcc-hard-013',
    category: 'Men of the Bible',
    difficulty: 'Hard',
    grid: [
      '#URIAH',
      'N##D##',
      'U#ADAH',
      'NEBO#U',
      '##B##R',
      'AMASA#',
    ],
  },
  {
    id: 'flcc-hard-014',
    category: 'Theology',
    difficulty: 'Hard',
    grid: [
      '#HADES',
      'C#M###',
      'O#OATH',
      'SAND#I',
      '###A#N',
      'PEARL#',
    ],
  },
  {
    id: 'flcc-hard-015',
    category: 'Bible Numbers',
    difficulty: 'Hard',
    grid: [
      '#AXE#Z',
      'S##L#I',
      'EPHA#M',
      'V#OMER',
      'E#R##I',
      'N#NOB#',
    ],
  },
  {
    id: 'flcc-hard-016',
    category: 'Scripture Detective',
    difficulty: 'Hard',
    grid: [
      'B#SEER',
      'U##Z##',
      'ZOAR##',
      '##RACA',
      '##B##S',
      'BOAZ#A',
    ],
  },
  {
    id: 'flcc-hard-017',
    category: 'Who Am I?',
    difficulty: 'Hard',
    grid: [
      '##JEHU',
      'C##L##',
      'U#JAIR',
      'PUAH#E',
      '##E##U',
      'TOLA##',
    ],
  },
  {
    id: 'flcc-hard-018',
    category: 'Lesser-Known People',
    difficulty: 'Hard',
    grid: [
      '#NER#A',
      '##L##L',
      'EHUD#M',
      'L#LOIS',
      'O##O##',
      'N#IRA#',
    ],
  },
  {
    id: 'flcc-hard-019',
    category: 'Bible Geography',
    difficulty: 'Hard',
    grid: [
      '#CANA#',
      '##N##O',
      'D#NAIN',
      'ETAM#O',
      'W##O##',
      '#SUSA#',
    ],
  },
  {
    id: 'flcc-hard-020',
    category: 'Objects & Symbols',
    difficulty: 'Hard',
    grid: [
      '#BEAM#',
      'L#L###',
      'URIM#H',
      'Z#MITE',
      '###N#N',
      '#GOAD#',
    ],
  },
  {
    id: 'flcc-hard-021',
    category: 'Places & Cities',
    difficulty: 'Hard',
    grid: [
      'SARDIS',
      '##O##H',
      'GAD##U',
      'A##HUR',
      'T##I##',
      'HINNOM',
    ],
  },
  {
    id: 'flcc-hard-022',
    category: 'New Testament',
    difficulty: 'Hard',
    grid: [
      'EMMAUS',
      '#Y###I',
      '#R#DAN',
      'OAK#L#',
      'I###O#',
      'LEAVEN',
    ],
  },
  {
    id: 'flcc-hard-023',
    category: 'Old Testament',
    difficulty: 'Hard',
    grid: [
      'CENSER',
      '##O#B#',
      'CAB#A#',
      '#H#ELI',
      '#A#R##',
      'UZZIAH',
    ],
  },
  {
    id: 'flcc-hard-024',
    category: 'Bible History',
    difficulty: 'Hard',
    grid: [
      'SISERA',
      'E###E#',
      'A##PUL',
      'HAM##E',
      '#S###H',
      'VASHTI',
    ],
  },
  {
    id: 'flcc-hard-025',
    category: 'Theology',
    difficulty: 'Hard',
    grid: [
      '#HOSEA',
      'W##P##',
      'ABBA#A',
      'Y#ONYX',
      '##A##E',
      'UZZAH#',
    ],
  },
  {
    id: 'flcc-hard-026',
    category: 'Who Am I?',
    difficulty: 'Hard',
    grid: [
      'ZERESH',
      'I###E#',
      'NER#E#',
      '#L#IRA',
      '#O###W',
      'MICHAL',
    ],
  },
  {
    id: 'flcc-hard-027',
    category: 'Places & Cities',
    difficulty: 'Hard',
    grid: [
      'GIBEON',
      '##U##A',
      'LUZ##R',
      'A##LOD',
      'M##O##',
      'PISGAH',
    ],
  },
  {
    id: 'flcc-hard-028',
    category: 'New Testament',
    difficulty: 'Hard',
    grid: [
      'LYSTRA',
      '#O###R',
      '#K#ROD',
      'HEN#A#',
      'I###T#',
      'NYMPHA',
    ],
  },
  {
    id: 'flcc-hard-029',
    category: 'Old Testament',
    difficulty: 'Hard',
    grid: [
      'GILGAL',
      'A###M#',
      'DEW#O#',
      '#L#ONO',
      '#A###I',
      'SHEKEL',
    ],
  },
  {
    id: 'flcc-hard-030',
    category: 'Who Am I?',
    difficulty: 'Hard',
    grid: [
      'AENEAS',
      'C##W#H',
      'H##ERI',
      'SIN##M',
      'A#U##E',
      'HANANI',
    ],
  },
  {
    id: 'flcc-hard-031',
    category: 'New Testament',
    difficulty: 'Hard',
    grid: [
      'D#COS#',
      'O#A###',
      'VINE#L',
      'E#ALOE',
      '###I#H',
      '#HAM#I',
    ],
  },
];
