/* =============================================================================
   THE QUESTION BANK
   -----------------------------------------------------------------------------
   Every question carries `ref`: the passage that settles it. It is shown after
   the answer, right or wrong, so a child who disagrees can go and check — and
   so that nothing can enter this bank that nobody could point to in a Bible.
   The test suite fails if a question has no reference, no correct answer, or
   names a story that does not exist.

   `tier` is a floor, not a label: a question tagged `young` is asked of
   everybody, `middle` of the ten-year-olds and up, `older` only of the
   teenagers. So the seven-year-old's quiz is genuinely shorter and genuinely
   easier, without a separate bank to keep in step.

   Questions are written to be answerable from the story text at that tier.
   A question a child could not have answered from what they just read is a
   trick, and it teaches them that the quiz is the enemy.
   ========================================================================== */

export const QUESTIONS = [
  // ── In the Beginning ──────────────────────────────────────────────────────
  { story: 'creation', tier: 'young', ref: 'Genesis 1:3',
    q: 'What was the first thing God made?',
    a: ['Light', 'Fish', 'Mountains', 'People'], correct: 0 },
  { story: 'creation', tier: 'young', ref: 'Genesis 1:27',
    q: 'What did God make last?',
    a: ['People', 'Stars', 'Trees', 'Birds'], correct: 0 },
  { story: 'creation', tier: 'young', ref: 'Genesis 1:31',
    q: 'What did God say about everything he had made?',
    a: ['It was very good', 'It was too noisy', 'It was almost right', 'It was finished'], correct: 0 },
  { story: 'creation', tier: 'middle', ref: 'Genesis 1:27',
    q: 'What is different about how people were made?',
    a: ['They were made in God\'s own image', 'They were made first', 'They were made from light', 'They were made on the sixth night'], correct: 0 },
  { story: 'creation', tier: 'middle', ref: 'Genesis 2:2-3',
    q: 'What happened on the seventh day?',
    a: ['God rested, and made the day holy', 'God made the animals', 'God made the sea', 'Nothing is recorded'], correct: 0 },
  { story: 'creation', tier: 'older', ref: 'Genesis 1:28',
    q: 'What job were human beings given in Genesis 1?',
    a: ['To rule over and care for the earth', 'To build a temple', 'To name the stars', 'To keep the garden secret'], correct: 0 },
  { story: 'creation', tier: 'older', ref: 'Genesis 1:1',
    q: 'How does Genesis argue that God exists?',
    a: ['It does not — it begins with him already there', 'By listing miracles', 'By quoting other nations', 'By describing a battle among gods'], correct: 0 },

  // ── The Choice in the Garden ──────────────────────────────────────────────
  { story: 'the-fall', tier: 'young', ref: 'Genesis 2:16-17',
    q: 'How many trees were Adam and Eve told not to eat from?',
    a: ['One', 'All of them', 'Seven', 'None'], correct: 0 },
  { story: 'the-fall', tier: 'young', ref: 'Genesis 3:8',
    q: 'What did Adam and Eve do after they disobeyed?',
    a: ['They hid from God', 'They ran away to another country', 'They planted a new tree', 'They told God straight away'], correct: 0 },
  { story: 'the-fall', tier: 'young', ref: 'Genesis 3:9',
    q: 'What did God say when he came into the garden?',
    a: ['"Where are you?"', '"Go away."', '"I am not listening."', 'Nothing at all'], correct: 0 },
  { story: 'the-fall', tier: 'middle', ref: 'Genesis 3:4-5',
    q: 'What did the serpent suggest about God?',
    a: ['That God was holding something back from them', 'That God did not exist', 'That God was asleep', 'That God had made a mistake'], correct: 0 },
  { story: 'the-fall', tier: 'middle', ref: 'Genesis 3:12-13',
    q: 'When God asked what had happened, what did Adam and Eve do?',
    a: ['They blamed somebody else', 'They confessed immediately', 'They said nothing', 'They ran away'], correct: 0 },
  { story: 'the-fall', tier: 'older', ref: 'Genesis 3:15',
    q: 'What does God say in the middle of the consequences?',
    a: ['That the woman\'s offspring will crush the serpent', 'That the garden will be rebuilt', 'That the serpent will be forgiven', 'That Adam will live forever'], correct: 0 },
  { story: 'the-fall', tier: 'older', ref: 'Genesis 3:9',
    q: 'Why is it significant that God\'s first word is a question?',
    a: ['He comes looking for them and invites them to answer', 'He does not know where they are', 'He has forgotten the rule', 'He is asking the serpent'], correct: 0 },

  // ── Noah and the Flood ────────────────────────────────────────────────────
  { story: 'noah', tier: 'young', ref: 'Genesis 6:14',
    q: 'What did God tell Noah to build?',
    a: ['A very large boat', 'A tower', 'A city wall', 'A bridge'], correct: 0 },
  { story: 'noah', tier: 'young', ref: 'Genesis 9:13',
    q: 'What did God put in the sky as a promise?',
    a: ['A rainbow', 'A star', 'A cloud', 'A dove'], correct: 0 },
  { story: 'noah', tier: 'young', ref: 'Genesis 6:9',
    q: 'What is said about Noah?',
    a: ['He walked with God', 'He was the strongest man alive', 'He was a king', 'He could sail any ship'], correct: 0 },
  { story: 'noah', tier: 'middle', ref: 'Genesis 6:6',
    q: 'How does Genesis describe God\'s reaction to human violence?',
    a: ['It grieved him to his heart', 'It surprised him', 'He ignored it', 'He laughed at it'], correct: 0 },
  { story: 'noah', tier: 'middle', ref: 'Genesis 8:20',
    q: 'What did Noah do first when he came out onto dry ground?',
    a: ['He built an altar and worshipped', 'He built a house', 'He planted a field', 'He counted the animals'], correct: 0 },
  { story: 'noah', tier: 'older', ref: 'Genesis 9:9-10',
    q: 'Who is included in the covenant God makes after the flood?',
    a: ['Noah and every living creature', 'Noah alone', 'Only Noah\'s sons', 'Only future kings'], correct: 0 },
  { story: 'noah', tier: 'older', ref: 'Genesis 8:21-22',
    q: 'What condition does God attach to his promise never to flood the earth again?',
    a: ['None — the promise is one-sided', 'That people obey ten rules', 'That Noah offers a sacrifice each year', 'That the ark is kept forever'], correct: 0 },

  // ── A Promise to Abraham ──────────────────────────────────────────────────
  { story: 'abraham', tier: 'young', ref: 'Genesis 12:1',
    q: 'What did God tell Abraham to do?',
    a: ['Leave his home and go to a new land', 'Build a boat', 'Become a soldier', 'Stay where he was'], correct: 0 },
  { story: 'abraham', tier: 'young', ref: 'Genesis 15:5',
    q: 'God said Abraham\'s family would be as many as what?',
    a: ['The stars', 'The mountains', 'The rivers', 'The days of the year'], correct: 0 },
  { story: 'abraham', tier: 'young', ref: 'Genesis 12:4',
    q: 'Did Abraham know where he was going?',
    a: ['No, but he went anyway', 'Yes, he had a map', 'Yes, he had been before', 'He never left'], correct: 0 },
  { story: 'abraham', tier: 'middle', ref: 'Genesis 12:3',
    q: 'What did God promise would happen through Abraham?',
    a: ['Every family on earth would be blessed', 'He would become a king', 'He would never be sad', 'His enemies would vanish'], correct: 0 },
  { story: 'abraham', tier: 'middle', ref: 'Genesis 12:4',
    q: 'How old was Abram when he left Haran?',
    a: ['Seventy-five', 'Forty', 'Ninety-nine', 'Twenty'], correct: 0 },
  { story: 'abraham', tier: 'older', ref: 'Genesis 15:6',
    q: 'What does Genesis say was credited to Abraham as righteousness?',
    a: ['That he believed God', 'That he built an altar', 'That he gave a tenth', 'That he kept the law'], correct: 0 },
  { story: 'abraham', tier: 'older', ref: 'Genesis 15:12, 17',
    q: 'When the covenant was formalised in Genesis 15, what was Abram doing?',
    a: ['Sleeping — only God passed between the pieces', 'Walking the path with God', 'Offering a prayer', 'Writing the terms down'], correct: 0 },

  // ── Joseph and His Brothers ───────────────────────────────────────────────
  { story: 'joseph', tier: 'young', ref: 'Genesis 37:28',
    q: 'What did Joseph\'s brothers do to him?',
    a: ['Sold him to traders going to Egypt', 'Sent him to school', 'Made him king', 'Took him home'], correct: 0 },
  { story: 'joseph', tier: 'young', ref: 'Genesis 41:41',
    q: 'What did the king of Egypt finally put Joseph in charge of?',
    a: ['The whole country', 'The royal garden', 'One small village', 'The army only'], correct: 0 },
  { story: 'joseph', tier: 'young', ref: 'Genesis 45:15',
    q: 'What did Joseph do when he saw his brothers again?',
    a: ['He wept, and fed them', 'He had them arrested', 'He sent them away', 'He did not recognise them'], correct: 0 },
  { story: 'joseph', tier: 'middle', ref: 'Genesis 39:20-21',
    q: 'Why was Joseph put in prison?',
    a: ['He was accused of something he had not done', 'He stole grain', 'He ran away', 'He argued with the king'], correct: 0 },
  { story: 'joseph', tier: 'middle', ref: 'Genesis 39:2, 21',
    q: 'What line does Genesis repeat throughout Joseph\'s hardest years?',
    a: ['That the LORD was with Joseph', 'That Joseph was clever', 'That Joseph never cried', 'That Joseph was owed an apology'], correct: 0 },
  { story: 'joseph', tier: 'older', ref: 'Genesis 50:20',
    q: 'What does Joseph say to his brothers at the end?',
    a: ['They meant evil, but God meant it for good', 'It never really hurt him', 'It was all a misunderstanding', 'He would take revenge later'], correct: 0 },
  { story: 'joseph', tier: 'older', ref: 'Genesis 50:20',
    q: 'Who is the only person in the story with the standing to say Genesis 50:20?',
    a: ['Joseph, about his own life', 'Any bystander, about anyone', 'His brothers, about Joseph', 'Pharaoh, about Egypt'], correct: 0 },

  // ── Let My People Go ──────────────────────────────────────────────────────
  { story: 'moses-exodus', tier: 'young', ref: 'Exodus 3:2',
    q: 'How did God first speak to Moses?',
    a: ['From a bush that burned but was not burned up', 'In a letter', 'Through his brother', 'From a cloud in the palace'], correct: 0 },
  { story: 'moses-exodus', tier: 'young', ref: 'Exodus 5:1',
    q: 'What message did Moses take to Pharaoh?',
    a: ['"Let my people go"', '"Give us gold"', '"Build us a city"', '"We will stay"'], correct: 0 },
  { story: 'moses-exodus', tier: 'young', ref: 'Exodus 14:21-22',
    q: 'How did the people get across the sea?',
    a: ['God opened a dry path through it', 'They built boats', 'They swam', 'They walked around it'], correct: 0 },
  { story: 'moses-exodus', tier: 'middle', ref: 'Exodus 2:23-25',
    q: 'What does Exodus say started the rescue?',
    a: ['God heard the people crying out', 'Moses volunteered', 'Pharaoh changed his mind', 'A drought'], correct: 0 },
  { story: 'moses-exodus', tier: 'middle', ref: 'Exodus 14:13-14',
    q: 'What were the people told to do at the edge of the sea?',
    a: ['Stand still and watch God rescue them', 'Attack the Egyptians', 'Turn back', 'Build a raft'], correct: 0 },
  { story: 'moses-exodus', tier: 'older', ref: 'Exodus 3:14',
    q: 'What name did God give Moses at the bush?',
    a: ['I AM WHO I AM', 'The Almighty of Sinai', 'The God of Egypt', 'He would not give one'], correct: 0 },
  { story: 'moses-exodus', tier: 'older', ref: 'Exodus 12:12',
    q: 'What were the plagues aimed at?',
    a: ['The gods of Egypt', 'Egypt\'s army', 'Egypt\'s farmland only', 'Nothing in particular'], correct: 0 },

  // ── Ten Words on the Mountain ─────────────────────────────────────────────
  { story: 'ten-commandments', tier: 'young', ref: 'Exodus 20:1-17',
    q: 'How many commandments did God give at the mountain?',
    a: ['Ten', 'Three', 'Twenty', 'One hundred'], correct: 0 },
  { story: 'ten-commandments', tier: 'young', ref: 'Exodus 19:18',
    q: 'What was the mountain like when God came down?',
    a: ['Smoking and shaking', 'Quiet and green', 'Covered in snow', 'Full of people'], correct: 0 },
  { story: 'ten-commandments', tier: 'young', ref: 'Exodus 20:8',
    q: 'What does the fourth commandment tell people to do?',
    a: ['Keep one day a week for rest', 'Work every day', 'Give away their house', 'Travel to Egypt'], correct: 0 },
  { story: 'ten-commandments', tier: 'middle', ref: 'Exodus 20:2',
    q: 'What comes before the first commandment?',
    a: ['A reminder that God rescued them from Egypt', 'A list of punishments', 'A census', 'A prayer from Moses'], correct: 0 },
  { story: 'ten-commandments', tier: 'middle', ref: 'Exodus 20:3-17',
    q: 'How do the ten commandments divide up?',
    a: ['Four about God, six about other people', 'Five and five', 'All ten about God', 'All ten about worship'], correct: 0 },
  { story: 'ten-commandments', tier: 'older', ref: 'Exodus 20:10',
    q: 'Who else is named as resting in the sabbath command?',
    a: ['Servants, foreigners and animals', 'Only the head of the family', 'Only priests', 'Only children'], correct: 0 },
  { story: 'ten-commandments', tier: 'older', ref: 'Matthew 22:37-40',
    q: 'How did Jesus summarise the commandments?',
    a: ['Love God, and love your neighbour as yourself', 'Keep the sabbath above all', 'Obey the priests', 'He said they no longer applied'], correct: 0 },

  // ── The Walls of Jericho ──────────────────────────────────────────────────
  { story: 'jericho', tier: 'young', ref: 'Joshua 6:3-4',
    q: 'How many days did the people march around Jericho?',
    a: ['Seven', 'Two', 'Forty', 'One'], correct: 0 },
  { story: 'jericho', tier: 'young', ref: 'Joshua 6:20',
    q: 'What happened when the people shouted?',
    a: ['The walls fell down', 'It started to rain', 'The gates opened', 'The army ran away'], correct: 0 },
  { story: 'jericho', tier: 'young', ref: 'Joshua 1:1-2',
    q: 'Who led the people after Moses?',
    a: ['Joshua', 'Aaron', 'Caleb', 'Gideon'], correct: 0 },
  { story: 'jericho', tier: 'middle', ref: 'Joshua 1:9',
    q: 'What did God tell Joshua before any of it began?',
    a: ['To be strong and courageous', 'To build a wall', 'To wait a year', 'To count the soldiers'], correct: 0 },
  { story: 'jericho', tier: 'middle', ref: 'Joshua 6:25',
    q: 'Whose household was spared when Jericho fell?',
    a: ['Rahab\'s', 'The king\'s', 'The priests\'', 'Nobody\'s'], correct: 0 },
  { story: 'jericho', tier: 'older', ref: 'Matthew 1:5',
    q: 'Where does Rahab appear later in the Bible?',
    a: ['In the family line of Jesus', 'In the book of Kings', 'Nowhere else', 'In the Psalms'], correct: 0 },
  { story: 'jericho', tier: 'older', ref: 'Joshua 6:2',
    q: 'Why was the plan for Jericho so unlike a military strategy?',
    a: ['So nobody could claim the credit for the victory', 'Because Israel had no weapons', 'Because the walls were already cracked', 'Because Joshua was inexperienced'], correct: 0 },

  // ── Gideon and the Three Hundred ──────────────────────────────────────────
  { story: 'gideon', tier: 'young', ref: 'Judges 6:12',
    q: 'What did the angel call Gideon?',
    a: ['A mighty warrior', 'A farmer', 'A little boy', 'A king'], correct: 0 },
  { story: 'gideon', tier: 'young', ref: 'Judges 7:7',
    q: 'How many men did Gideon have at the end?',
    a: ['Three hundred', 'Thirty-two thousand', 'Ten', 'One hundred'], correct: 0 },
  { story: 'gideon', tier: 'young', ref: 'Judges 6:11',
    q: 'What was Gideon doing when the angel found him?',
    a: ['Hiding while he threshed wheat', 'Leading an army', 'Sleeping', 'Fishing'], correct: 0 },
  { story: 'gideon', tier: 'middle', ref: 'Judges 6:36-40',
    q: 'How many signs did Gideon ask God for?',
    a: ['Two, opposite to each other', 'None', 'Seven', 'One only'], correct: 0 },
  { story: 'gideon', tier: 'middle', ref: 'Judges 6:15',
    q: 'How did Gideon describe himself?',
    a: ['The least in the weakest family', 'The strongest man in Israel', 'A trained soldier', 'A prophet'], correct: 0 },
  { story: 'gideon', tier: 'older', ref: 'Judges 7:2',
    q: 'Why did God reduce the army?',
    a: ['So Israel could not boast that their own hand had saved them', 'To save food', 'Because the men were disloyal', 'To move faster'], correct: 0 },
  { story: 'gideon', tier: 'older', ref: 'Judges 8:27',
    q: 'How does Gideon\'s story end?',
    a: ['With a warning — the gold he made became a snare', 'With him becoming king', 'With him leaving Israel', 'With no more trouble at all'], correct: 0 },

  // ── Ruth Stays ────────────────────────────────────────────────────────────
  { story: 'ruth', tier: 'young', ref: 'Ruth 1:16',
    q: 'What did Ruth say to Naomi?',
    a: ['"Where you go, I will go"', '"I am going home"', '"Wait for me here"', '"I will send money"'], correct: 0 },
  { story: 'ruth', tier: 'young', ref: 'Ruth 2:2-3',
    q: 'How did Ruth get food for herself and Naomi?',
    a: ['She gathered leftover grain in the fields', 'She bought it', 'She begged at the gate', 'She was given it by the king'], correct: 0 },
  { story: 'ruth', tier: 'young', ref: 'Ruth 4:17',
    q: 'Who was Ruth\'s famous great-grandson?',
    a: ['King David', 'Moses', 'Samson', 'Solomon'], correct: 0 },
  { story: 'ruth', tier: 'middle', ref: 'Ruth 1:4',
    q: 'Where was Ruth from?',
    a: ['Moab — she was a foreigner in Israel', 'Bethlehem', 'Egypt', 'Jericho'], correct: 0 },
  { story: 'ruth', tier: 'middle', ref: 'Ruth 1:20',
    q: 'What did Naomi ask people to call her?',
    a: ['Mara, meaning bitter', 'Ruth', 'Nothing at all', 'Blessed'], correct: 0 },
  { story: 'ruth', tier: 'older', ref: 'Leviticus 19:9-10',
    q: 'Which law made Ruth\'s gleaning possible?',
    a: ['Harvesters had to leave the field edges for the poor', 'Widows were paid by the state', 'Foreigners were given land', 'Landowners had to hire anyone who asked'], correct: 0 },
  { story: 'ruth', tier: 'older', ref: 'Ruth 1:1',
    q: 'When is the book of Ruth set?',
    a: ['In the days of the judges', 'During the exile', 'After the resurrection', 'Before the flood'], correct: 0 },

  // ── David and Goliath ─────────────────────────────────────────────────────
  { story: 'david-goliath', tier: 'young', ref: '1 Samuel 17:40',
    q: 'What did David take with him to fight Goliath?',
    a: ['A sling and five smooth stones', 'A sword and shield', 'A bow', 'Nothing at all'], correct: 0 },
  { story: 'david-goliath', tier: 'young', ref: '1 Samuel 17:15',
    q: 'What was David\'s job before this?',
    a: ['Looking after sheep', 'Building houses', 'Fishing', 'Serving in the army'], correct: 0 },
  { story: 'david-goliath', tier: 'young', ref: '1 Samuel 17:38-39',
    q: 'Why did David take off Saul\'s armour?',
    a: ['He had never used it and it did not fit', 'It was too shiny', 'Saul asked for it back', 'It was broken'], correct: 0 },
  { story: 'david-goliath', tier: 'middle', ref: '1 Samuel 17:16',
    q: 'How long had Goliath been challenging Israel?',
    a: ['Forty days', 'One morning', 'Three years', 'A week'], correct: 0 },
  { story: 'david-goliath', tier: 'middle', ref: '1 Samuel 17:34-36',
    q: 'What experience did David base his confidence on?',
    a: ['Protecting his sheep from a lion and a bear', 'Training with the army', 'A dream', 'Winning a contest'], correct: 0 },
  { story: 'david-goliath', tier: 'older', ref: '1 Samuel 17:28, 33',
    q: 'Who opposed David besides Goliath?',
    a: ['His own brother, and King Saul', 'Only the Philistines', 'His father', 'Nobody'], correct: 0 },
  { story: 'david-goliath', tier: 'older', ref: '1 Samuel 17:47',
    q: 'What did David say the battle was about?',
    a: ['That the battle belonged to the LORD', 'That he was the better fighter', 'That Israel deserved to win', 'That Goliath was overrated'], correct: 0 },

  // ── Solomon Asks for Wisdom ───────────────────────────────────────────────
  { story: 'solomon', tier: 'young', ref: '1 Kings 3:9',
    q: 'What did Solomon ask God for?',
    a: ['Wisdom to lead people well', 'Gold', 'A long life', 'A bigger army'], correct: 0 },
  { story: 'solomon', tier: 'young', ref: '1 Kings 3:13',
    q: 'What did God give Solomon that he had not asked for?',
    a: ['Riches and honour', 'A new country', 'A brother', 'A ship'], correct: 0 },
  { story: 'solomon', tier: 'young', ref: '1 Kings 3:5',
    q: 'How did God make his offer to Solomon?',
    a: ['In a dream', 'In a letter', 'Through an angel at the gate', 'Through his mother'], correct: 0 },
  { story: 'solomon', tier: 'middle', ref: '1 Kings 3:7',
    q: 'How did Solomon describe himself in his prayer?',
    a: ['As a little child who did not know how to lead', 'As the wisest man alive', 'As his father\'s equal', 'As a soldier'], correct: 0 },
  { story: 'solomon', tier: 'middle', ref: '1 Kings 3:10-11',
    q: 'Why was God pleased with the request?',
    a: ['Solomon asked for the people\'s sake, not his own', 'It was the shortest prayer', 'It was made at the temple', 'He asked for nothing'], correct: 0 },
  { story: 'solomon', tier: 'older', ref: 'Ecclesiastes 1:2',
    q: 'What does Ecclesiastes conclude about wealth, work and pleasure?',
    a: ['That chasing them is like chasing vapour', 'That they satisfy completely', 'That they are forbidden', 'That only the rich may have them'], correct: 0 },
  { story: 'solomon', tier: 'older', ref: '1 Kings 11:4',
    q: 'What happened to Solomon later in life?',
    a: ['His heart was turned away from God', 'He gave up the throne', 'He wrote the Psalms', 'He led Israel back to the desert'], correct: 0 },

  // ── Fire on Mount Carmel ──────────────────────────────────────────────────
  { story: 'elijah-carmel', tier: 'young', ref: '1 Kings 18:38',
    q: 'What came down on Elijah\'s altar?',
    a: ['Fire from heaven', 'Rain', 'Hail', 'A cloud'], correct: 0 },
  { story: 'elijah-carmel', tier: 'young', ref: '1 Kings 18:33-35',
    q: 'What did Elijah pour over his altar first?',
    a: ['Water', 'Oil', 'Sand', 'Nothing'], correct: 0 },
  { story: 'elijah-carmel', tier: 'young', ref: '1 Kings 18:26',
    q: 'What happened when the prophets of Baal called on their god?',
    a: ['Nothing at all', 'A small fire started', 'It rained', 'Baal answered'], correct: 0 },
  { story: 'elijah-carmel', tier: 'middle', ref: '1 Kings 18:21',
    q: 'What question did Elijah put to the people?',
    a: ['How long will you keep limping between two opinions?', 'Who will fight for me?', 'Where is your king?', 'Why is there no rain?'], correct: 0 },
  { story: 'elijah-carmel', tier: 'middle', ref: '1 Kings 18:22',
    q: 'How many prophets of Baal were there?',
    a: ['Four hundred and fifty', 'Twelve', 'Seven', 'Three thousand'], correct: 0 },
  { story: 'elijah-carmel', tier: 'older', ref: '1 Kings 19:3-4',
    q: 'What happened to Elijah straight after this victory?',
    a: ['He fled in fear and asked to die', 'He was made king', 'He built a temple', 'He never doubted again'], correct: 0 },
  { story: 'elijah-carmel', tier: 'older', ref: '1 Kings 19:11-12',
    q: 'How did God speak to Elijah at Horeb?',
    a: ['In a low whisper, not the wind, earthquake or fire', 'In an earthquake', 'In a great fire', 'He did not speak'], correct: 0 },

  // ── Daniel and the Lions ──────────────────────────────────────────────────
  { story: 'daniel-lions', tier: 'young', ref: 'Daniel 6:10',
    q: 'How often did Daniel pray?',
    a: ['Three times a day', 'Once a week', 'Only at night', 'Only in secret'], correct: 0 },
  { story: 'daniel-lions', tier: 'young', ref: 'Daniel 6:22',
    q: 'What happened in the lions\' den?',
    a: ['God shut the lions\' mouths', 'The lions were asleep', 'Daniel fought them', 'The king rescued him'], correct: 0 },
  { story: 'daniel-lions', tier: 'young', ref: 'Daniel 6:7',
    q: 'What did the new law say?',
    a: ['Nobody may pray to anyone except the king', 'Nobody may leave the city', 'Everybody must give gold', 'Nobody may open a window'], correct: 0 },
  { story: 'daniel-lions', tier: 'middle', ref: 'Daniel 6:10',
    q: 'What did Daniel change after the law was signed?',
    a: ['Nothing — he prayed exactly as before', 'He prayed silently', 'He prayed in a cellar', 'He stopped for thirty days'], correct: 0 },
  { story: 'daniel-lions', tier: 'middle', ref: 'Daniel 6:18',
    q: 'How did the king spend the night?',
    a: ['Awake, without eating', 'Feasting', 'Asleep', 'Hunting'], correct: 0 },
  { story: 'daniel-lions', tier: 'older', ref: 'Daniel 6:4-5',
    q: 'What did Daniel\'s enemies admit about him?',
    a: ['They could find no fault except concerning his God', 'That he stole money', 'That he was lazy', 'That he was a poor official'], correct: 0 },
  { story: 'daniel-lions', tier: 'older', ref: 'Daniel 6:3',
    q: 'What was Daniel\'s position in the empire?',
    a: ['A senior official the king planned to promote further', 'A prisoner', 'A temple priest', 'A soldier'], correct: 0 },

  // ── Jonah Runs Away ───────────────────────────────────────────────────────
  { story: 'jonah', tier: 'young', ref: 'Jonah 1:3',
    q: 'What did Jonah do when God told him to go to Nineveh?',
    a: ['He got on a boat going the other way', 'He went straight away', 'He hid in his house', 'He sent a friend'], correct: 0 },
  { story: 'jonah', tier: 'young', ref: 'Jonah 1:17',
    q: 'What swallowed Jonah?',
    a: ['A great fish', 'A whale shark', 'A crocodile', 'Nothing did'], correct: 0 },
  { story: 'jonah', tier: 'young', ref: 'Jonah 3:5',
    q: 'What did the people of Nineveh do when Jonah preached?',
    a: ['They believed God and turned from their wrong', 'They laughed at him', 'They put him in prison', 'They ignored him'], correct: 0 },
  { story: 'jonah', tier: 'middle', ref: 'Jonah 4:1',
    q: 'How did Jonah react when Nineveh was spared?',
    a: ['He was angry', 'He celebrated', 'He wrote a song', 'He went home quietly'], correct: 0 },
  { story: 'jonah', tier: 'middle', ref: 'Jonah 1:12',
    q: 'What did Jonah tell the sailors to do in the storm?',
    a: ['Throw him into the sea', 'Row harder', 'Pray to his God', 'Turn the ship around'], correct: 0 },
  { story: 'jonah', tier: 'older', ref: 'Jonah 4:2',
    q: 'Why does Jonah say he ran away in the first place?',
    a: ['He knew God was merciful and would spare Nineveh', 'He was afraid of the journey', 'He did not believe God', 'He was ill'], correct: 0 },
  { story: 'jonah', tier: 'older', ref: 'Jonah 4:11',
    q: 'How does the book of Jonah end?',
    a: ['With a question from God that Jonah never answers', 'With Jonah repenting', 'With Nineveh destroyed', 'With Jonah returning home'], correct: 0 },

  // ── Esther Speaks Up ──────────────────────────────────────────────────────
  { story: 'esther', tier: 'young', ref: 'Esther 2:17',
    q: 'Who did Esther become?',
    a: ['The queen', 'A soldier', 'A teacher', 'A judge'], correct: 0 },
  { story: 'esther', tier: 'young', ref: 'Esther 4:16',
    q: 'What did Esther say before going to the king?',
    a: ['"If I perish, I perish"', '"Send somebody else"', '"I am not afraid"', '"Wait a year"'], correct: 0 },
  { story: 'esther', tier: 'young', ref: 'Esther 4:16',
    q: 'What did Esther ask her people to do first?',
    a: ['Fast for three days', 'Leave the city', 'Write to the king', 'Hide their names'], correct: 0 },
  { story: 'esther', tier: 'middle', ref: 'Esther 4:11',
    q: 'Why was going to the king dangerous?',
    a: ['Approaching him uninvited could mean death', 'He was away at war', 'He did not speak her language', 'The palace was locked'], correct: 0 },
  { story: 'esther', tier: 'middle', ref: 'Esther 3:8-9',
    q: 'What was Haman\'s plan?',
    a: ['To destroy every Jew in the empire', 'To take Mordecai\'s house', 'To become king', 'To raise taxes'], correct: 0 },
  { story: 'esther', tier: 'older', ref: 'Esther 4:14',
    q: 'What was Mordecai\'s argument to Esther?',
    a: ['She would not escape either, and may have come to her place for this moment', 'That she was safe in the palace', 'That God had promised to protect her', 'That somebody else would act'], correct: 0 },
  { story: 'esther', tier: 'older', ref: 'Esther 1-10',
    q: 'What is unusual about the book of Esther?',
    a: ['God is never mentioned in it', 'It has no ending', 'It is written as a poem', 'It names no people'], correct: 0 },

  // ── The Birth of Jesus ────────────────────────────────────────────────────
  { story: 'birth-of-jesus', tier: 'young', ref: 'Luke 1:26-31',
    q: 'Who told Mary she would have a son?',
    a: ['The angel Gabriel', 'A shepherd', 'Joseph', 'A king'], correct: 0 },
  { story: 'birth-of-jesus', tier: 'young', ref: 'Luke 2:7',
    q: 'Where was Jesus laid after he was born?',
    a: ['In a manger, where the animals ate', 'In a palace bed', 'In a boat', 'In a temple'], correct: 0 },
  { story: 'birth-of-jesus', tier: 'young', ref: 'Luke 2:8-11',
    q: 'Who were the first people told the news?',
    a: ['Shepherds in the fields', 'Kings', 'Priests', 'Soldiers'], correct: 0 },
  { story: 'birth-of-jesus', tier: 'middle', ref: 'Luke 1:38',
    q: 'What was Mary\'s answer to the angel?',
    a: ['"Let it be to me according to your word"', '"Ask somebody else"', '"I do not believe you"', 'She said nothing'], correct: 0 },
  { story: 'birth-of-jesus', tier: 'middle', ref: 'Luke 2:1-4',
    q: 'Why were Mary and Joseph in Bethlehem?',
    a: ['A census required it', 'They were visiting family', 'They were escaping Herod', 'They had moved there'], correct: 0 },
  { story: 'birth-of-jesus', tier: 'older', ref: 'Luke 1:52-53',
    q: 'What is Mary\'s song, the Magnificat, about?',
    a: ['Rulers brought down and the hungry filled', 'The beauty of Bethlehem', 'Her own happiness only', 'The census'], correct: 0 },
  { story: 'birth-of-jesus', tier: 'older', ref: 'Matthew 1:23',
    q: 'What does the name Immanuel mean?',
    a: ['God with us', 'The promised one', 'Son of David', 'Light of the world'], correct: 0 },

  // ── Jesus Teaches on the Hillside ─────────────────────────────────────────
  { story: 'sermon-on-the-mount', tier: 'young', ref: 'Matthew 5:44',
    q: 'What did Jesus say to do about your enemies?',
    a: ['Love them and pray for them', 'Avoid them', 'Defeat them', 'Forget them'], correct: 0 },
  { story: 'sermon-on-the-mount', tier: 'young', ref: 'Matthew 6:9',
    q: 'How does the prayer Jesus taught begin?',
    a: ['"Our Father in heaven"', '"Listen, O God"', '"Bless this house"', '"Forgive me"'], correct: 0 },
  { story: 'sermon-on-the-mount', tier: 'young', ref: 'Matthew 5:14-16',
    q: 'What did Jesus say his followers are?',
    a: ['The light of the world', 'The strongest people', 'The rulers of the earth', 'The wisest teachers'], correct: 0 },
  { story: 'sermon-on-the-mount', tier: 'middle', ref: 'Matthew 5:3-10',
    q: 'Who does Jesus call blessed in the Beatitudes?',
    a: ['The poor in spirit, mourners, the meek, the persecuted', 'The rich and powerful', 'The clever', 'The religious leaders'], correct: 0 },
  { story: 'sermon-on-the-mount', tier: 'middle', ref: 'Matthew 6:1-4',
    q: 'What did Jesus warn about doing good deeds?',
    a: ['Do not do them to be seen doing them', 'Do them only on the sabbath', 'Do them only for family', 'Do not do them at all'], correct: 0 },
  { story: 'sermon-on-the-mount', tier: 'older', ref: 'Matthew 5:21-22',
    q: 'How does Jesus deepen the command against murder?',
    a: ['He traces it back to anger and contempt', 'He removes it', 'He applies it only to soldiers', 'He limits it to family'], correct: 0 },
  { story: 'sermon-on-the-mount', tier: 'older', ref: 'Matthew 7:24-27',
    q: 'What is the difference between the two builders?',
    a: ['One acts on Jesus\' words; the other only hears them', 'One is richer', 'One built faster', 'One had better weather'], correct: 0 },

  // ── The Son Who Came Home ─────────────────────────────────────────────────
  { story: 'lost-son', tier: 'young', ref: 'Luke 15:20',
    q: 'What did the father do when he saw his son coming home?',
    a: ['He ran to him and hugged him', 'He shut the door', 'He waited inside', 'He sent a servant'], correct: 0 },
  { story: 'lost-son', tier: 'young', ref: 'Luke 15:13',
    q: 'What did the younger son do with his father\'s money?',
    a: ['He spent it all', 'He saved it', 'He gave it away', 'He bought a farm'], correct: 0 },
  { story: 'lost-son', tier: 'young', ref: 'Luke 15:23-24',
    q: 'What did the father do when his son came home?',
    a: ['Threw a party', 'Made him work as a servant', 'Sent him away again', 'Said nothing'], correct: 0 },
  { story: 'lost-son', tier: 'middle', ref: 'Luke 15:28',
    q: 'How did the older brother react?',
    a: ['He was angry and would not go in', 'He joined the party', 'He went to find his brother', 'He forgave him at once'], correct: 0 },
  { story: 'lost-son', tier: 'middle', ref: 'Luke 15:1-2',
    q: 'Who was Jesus telling this story to?',
    a: ['People complaining that he ate with sinners', 'Roman soldiers', 'His family', 'Children'], correct: 0 },
  { story: 'lost-son', tier: 'older', ref: 'Luke 15:28-32',
    q: 'Why are there two lost sons in the parable?',
    a: ['The elder is lost at home, angry that grace was not earned', 'The elder also ran away', 'The father had a third son', 'The younger never returned'], correct: 0 },
  { story: 'lost-son', tier: 'older', ref: 'Luke 15:32',
    q: 'How does the parable end?',
    a: ['Unresolved — we never learn if the elder brother goes in', 'With both sons at the feast', 'With the elder brother leaving', 'With the father\'s death'], correct: 0 },

  // ── The Cross ─────────────────────────────────────────────────────────────
  { story: 'the-cross', tier: 'young', ref: 'Luke 23:34',
    q: 'What did Jesus pray for the people who hurt him?',
    a: ['That his Father would forgive them', 'That they would be punished', 'Nothing', 'That they would be quiet'], correct: 0 },
  { story: 'the-cross', tier: 'young', ref: 'Luke 23:44-45',
    q: 'What happened to the sky?',
    a: ['It went dark', 'It filled with stars', 'It turned red', 'Nothing changed'], correct: 0 },
  { story: 'the-cross', tier: 'young', ref: 'Luke 23:33',
    q: 'Who was crucified beside Jesus?',
    a: ['Two criminals', 'His disciples', 'Nobody', 'Two soldiers'], correct: 0 },
  { story: 'the-cross', tier: 'middle', ref: 'Luke 23:4, 14, 22',
    q: 'What did Pilate say about Jesus?',
    a: ['That he found no fault in him — and sentenced him anyway', 'That he was clearly guilty', 'That he would set him free', 'Nothing at all'], correct: 0 },
  { story: 'the-cross', tier: 'middle', ref: 'Luke 23:42-43',
    q: 'What did Jesus promise the criminal who asked to be remembered?',
    a: ['That he would be with him in paradise that day', 'That he would be released', 'That he would be judged later', 'Nothing'], correct: 0 },
  { story: 'the-cross', tier: 'older', ref: 'John 19:30',
    q: 'What did Jesus say at the very end?',
    a: ['"It is finished"', '"Let me go"', '"Begin again"', '"Remember me"'], correct: 0 },
  { story: 'the-cross', tier: 'older', ref: 'Luke 23:45',
    q: 'What happened to the curtain in the temple?',
    a: ['It tore in two', 'It was taken down', 'It caught fire', 'Nothing happened to it'], correct: 0 },

  // ── He Is Risen ───────────────────────────────────────────────────────────
  { story: 'resurrection', tier: 'young', ref: 'Luke 24:2-3',
    q: 'What did the women find at the tomb?',
    a: ['The stone rolled away and the tomb empty', 'Soldiers asleep', 'The stone still shut', 'Jesus\' body'], correct: 0 },
  { story: 'resurrection', tier: 'young', ref: 'Luke 24:6',
    q: 'What were the women told?',
    a: ['"He isn\'t here, but is risen"', '"Come back tomorrow"', '"Go home"', '"He has been taken away"'], correct: 0 },
  { story: 'resurrection', tier: 'young', ref: 'John 20:16',
    q: 'How did Mary Magdalene realise who Jesus was?',
    a: ['He said her name', 'He showed her a sign', 'Another disciple told her', 'She recognised his clothes'], correct: 0 },
  { story: 'resurrection', tier: 'middle', ref: 'John 20:24-28',
    q: 'What did Thomas say he needed?',
    a: ['To touch the wounds himself', 'To hear it from Peter', 'To see the empty tomb', 'To wait a week'], correct: 0 },
  { story: 'resurrection', tier: 'middle', ref: 'Luke 24:11',
    q: 'How did the disciples first react to the women\'s report?',
    a: ['They thought it was nonsense', 'They believed at once', 'They ran to tell others', 'They were not told'], correct: 0 },
  { story: 'resurrection', tier: 'older', ref: 'Luke 24:1-10',
    q: 'Why is it striking that women were the first witnesses?',
    a: ['A woman\'s testimony carried little weight then — nobody would invent it', 'They were the only believers left', 'They were the disciples\' leaders', 'They had asked to be'], correct: 0 },
  { story: 'resurrection', tier: 'older', ref: '1 Corinthians 15:14, 19',
    q: 'What does Paul say if Christ has not been raised?',
    a: ['Preaching and faith are worthless, and Christians are to be pitied', 'The teaching still stands', 'It makes little difference', 'The church should continue quietly'], correct: 0 },

  // ── The Church Begins ─────────────────────────────────────────────────────
  { story: 'pentecost', tier: 'young', ref: 'Acts 2:2',
    q: 'What did the disciples hear at Pentecost?',
    a: ['A sound like a rushing wind', 'A trumpet', 'Thunder', 'Singing'], correct: 0 },
  { story: 'pentecost', tier: 'young', ref: 'Acts 2:4',
    q: 'What could the disciples suddenly do?',
    a: ['Speak languages they had never learned', 'Fly', 'Heal every illness', 'Read minds'], correct: 0 },
  { story: 'pentecost', tier: 'young', ref: 'Acts 2:41',
    q: 'How many people believed that day?',
    a: ['About three thousand', 'Twelve', 'One hundred', 'Nobody'], correct: 0 },
  { story: 'pentecost', tier: 'middle', ref: 'Acts 2:14',
    q: 'Who preached to the crowd?',
    a: ['Peter', 'Paul', 'John', 'James'], correct: 0 },
  { story: 'pentecost', tier: 'middle', ref: 'Acts 2:42',
    q: 'What did the first church devote itself to?',
    a: ['Teaching, fellowship, breaking bread and prayer', 'Building a temple', 'Collecting taxes', 'Writing laws'], correct: 0 },
  { story: 'pentecost', tier: 'older', ref: 'Acts 2:8-11',
    q: 'What is significant about the languages at Pentecost?',
    a: ['Each person heard in their own language, rather than having to learn one', 'Only Hebrew was spoken', 'Nobody understood anything', 'The disciples used interpreters'], correct: 0 },
  { story: 'pentecost', tier: 'older', ref: 'Acts 2:44-45',
    q: 'What did the first believers do with their possessions?',
    a: ['Sold property to meet each other\'s needs', 'Kept them separate', 'Gave them to the temple', 'Nothing is recorded'], correct: 0 },

  // ── The Man Who Changed Sides ─────────────────────────────────────────────
  { story: 'paul', tier: 'young', ref: 'Acts 9:1-2',
    q: 'What was Saul doing before he met Jesus?',
    a: ['Arresting Christians', 'Teaching in the temple', 'Fishing', 'Building houses'], correct: 0 },
  { story: 'paul', tier: 'young', ref: 'Acts 9:8-9',
    q: 'What happened to Saul after the bright light?',
    a: ['He could not see for three days', 'He fell asleep', 'He ran home', 'He lost his voice'], correct: 0 },
  { story: 'paul', tier: 'young', ref: 'Acts 9:17',
    q: 'Who did God send to help Saul?',
    a: ['Ananias', 'Peter', 'Barnabas', 'Timothy'], correct: 0 },
  { story: 'paul', tier: 'middle', ref: 'Acts 9:4',
    q: 'What did the voice say on the road?',
    a: ['"Saul, Saul, why do you persecute me?"', '"Saul, come and follow me."', '"Saul, go home."', '"Saul, who are you?"'], correct: 0 },
  { story: 'paul', tier: 'middle', ref: 'Acts 9:13-14',
    q: 'How did Ananias respond to his assignment?',
    a: ['He argued with God about it, then went', 'He refused completely', 'He went without a word', 'He sent somebody else'], correct: 0 },
  { story: 'paul', tier: 'older', ref: 'Acts 9:4-5',
    q: 'Why does Jesus say "why do you persecute me" rather than "my followers"?',
    a: ['He identifies himself with his people', 'Saul had met him before', 'It is a mistranslation', 'He means the temple'], correct: 0 },
  { story: 'paul', tier: 'older', ref: 'Acts 9:26-27',
    q: 'How did the church in Jerusalem receive Saul?',
    a: ['They were afraid of him until Barnabas vouched for him', 'They welcomed him at once', 'They never accepted him', 'They made him a leader immediately'], correct: 0 },
];
