/**
 * ChallengesScene — Daily Challenge (resets every day) and Weekly
 * Challenge (resets every ISO week) cards. Both play a one-off level
 * generated by LevelGenerator.generateChallengeLevel(), scored against
 * a best-score/threshold rather than the campaign's star system.
 */
(function (global) {
  'use strict';

  class ChallengesScene extends Phaser.Scene {
    constructor() {
      super('Challenges');
    }

    create() {
      const C = global.FM_CONST.COLORS;
      const { width, height } = this.scale;
      this.cameras.main.setBackgroundColor(C.BACKGROUND);

      this.add.text(width / 2, 44, 'Challenges', {
        fontFamily: 'Inter, sans-serif',
        fontSize: '22px',
        fontStyle: '800',
        color: C.TEXT
      }).setOrigin(0.5);

      new global.FMButton(this, {
        x: 50,
        y: 40,
        width: 76,
        height: 40,
        label: '< Menu',
        variant: 'secondary',
        fontSize: 13,
        onClick: () => this.scene.start('Menu')
      });

      this._buildDailyCard(width / 2, 130);
      this._buildWeeklyCard(width / 2, 280);
    }

    _cardShell(x, y, accentHex, height) {
      const C = global.FM_CONST.COLORS;
      const width = Math.min(360, this.scale.width - 40);
      const container = this.add.container(x, y);

      const bg = this.add.graphics();
      bg.fillStyle(Phaser.Display.Color.HexStringToColor(C.SURFACE).color, 1);
      bg.fillRoundedRect(-width / 2, -height / 2, width, height, 18);
      bg.lineStyle(1.5, Phaser.Display.Color.HexStringToColor(C.BORDER).color, 1);
      bg.strokeRoundedRect(-width / 2, -height / 2, width, height, 18);
      container.add(bg);

      const stripe = this.add.graphics();
      stripe.fillStyle(Phaser.Display.Color.HexStringToColor(accentHex).color, 1);
      stripe.fillRoundedRect(-width / 2, -height / 2, 8, height, { tl: 18, bl: 18, tr: 0, br: 0 });
      container.add(stripe);

      container.setData('width', width);
      return container;
    }

    _buildDailyCard(x, y) {
      const C = global.FM_CONST.COLORS;
      const level = global.LevelManager.getChallengeLevel('daily');
      const d = global.FM_SAVE.data.dailyChallenge;
      const bestScore = d.dateKey === level.challengeKey ? d.bestScore : 0;

      const card = this._cardShell(x, y, C.ACCENT, 128);
      const w = card.getData('width');

      card.add(this.add.text(-w / 2 + 26, -40, 'Daily Challenge', {
        fontFamily: 'Inter, sans-serif', fontSize: '16px', fontStyle: '800', color: C.TEXT
      }).setOrigin(0, 0.5));

      card.add(this.add.text(-w / 2 + 26, -16, `Target score: ${level.objectives[0].target}`, {
        fontFamily: 'Inter, sans-serif', fontSize: '12px', color: C.TEXT_MUTED
      }).setOrigin(0, 0.5));

      card.add(this.add.text(-w / 2 + 26, 6, `Best today: ${bestScore}`, {
        fontFamily: 'Inter, sans-serif', fontSize: '12px', fontStyle: '600', color: C.TEXT
      }).setOrigin(0, 0.5));

      card.add(new global.FMButton(this, {
        x: 0,
        y: 44,
        width: w - 40,
        height: 42,
        label: bestScore > 0 ? 'Play Again' : 'Play',
        variant: 'primary',
        fontSize: 14,
        onClick: () => this.scene.start('Game', { challengeKind: 'daily' })
      }));
    }

    _buildWeeklyCard(x, y) {
      const C = global.FM_CONST.COLORS;
      const level = global.LevelManager.getChallengeLevel('weekly');
      const w2 = global.FM_SAVE.data.weeklyChallenge;
      const currentScore = w2.weekKey === level.challengeKey ? w2.score : 0;
      const completed = w2.weekKey === level.challengeKey && w2.completed;

      const card = this._cardShell(x, y, '#7C3AED', 148);
      const w = card.getData('width');

      card.add(this.add.text(-w / 2 + 26, -52, 'Weekly Challenge', {
        fontFamily: 'Inter, sans-serif', fontSize: '16px', fontStyle: '800', color: C.TEXT
      }).setOrigin(0, 0.5));

      card.add(this.add.text(-w / 2 + 26, -28, `Threshold: ${level.starThresholds[0]} pts`, {
        fontFamily: 'Inter, sans-serif', fontSize: '12px', color: C.TEXT_MUTED
      }).setOrigin(0, 0.5));

      card.add(this.add.text(-w / 2 + 26, -6, `Best this week: ${currentScore}`, {
        fontFamily: 'Inter, sans-serif', fontSize: '12px', fontStyle: '600', color: C.TEXT
      }).setOrigin(0, 0.5));

      card.add(this.add.text(-w / 2 + 26, 16, completed ? '✅ Reward claimed: +150 coins, +300 XP' : 'Reward: +150 coins, +300 XP', {
        fontFamily: 'Inter, sans-serif', fontSize: '11px', color: completed ? C.SUCCESS : C.TEXT_MUTED
      }).setOrigin(0, 0.5));

      card.add(new global.FMButton(this, {
        x: 0,
        y: 56,
        width: w - 40,
        height: 42,
        label: 'Play',
        variant: 'primary',
        fontSize: 14,
        onClick: () => this.scene.start('Game', { challengeKind: 'weekly' })
      }));
    }
  }

  global.ChallengesScene = ChallengesScene;
})(window);
