/**
 * Scripture — a 300-verse bank (King James Version, public domain),
 * grouped by the same 14 story themes as the world map so the verse
 * pool can later be filtered by world if desired. GameScene currently
 * draws uniformly at random across the whole pool after every
 * completed level, preferring verses the player hasn't seen recently
 * (tracked in SaveManager's `seenVerseIds`).
 *
 * Each entry: { ref, text, note, theme }
 *   ref   - book/chapter/verse citation
 *   text  - KJV verse text
 *   note  - one-sentence devotional takeaway
 *   theme - matches FM_CONST.WORLDS[].theme
 */
(function (global) {
  'use strict';

  const VERSES = [
    // ---------------- Creation (22) ----------------
    { ref: 'Genesis 1:1', text: 'In the beginning God created the heaven and the earth.', note: 'Every story — including yours — begins with God.', theme: 'creation' },
    { ref: 'Genesis 1:3', text: 'And God said, Let there be light: and there was light.', note: "God's word doesn't just describe reality, it creates it.", theme: 'creation' },
    { ref: 'Genesis 1:27', text: 'So God created man in his own image, in the image of God created he him; male and female created he them.', note: 'You bear the very image of your Creator.', theme: 'creation' },
    { ref: 'Genesis 1:31', text: 'And God saw every thing that he had made, and, behold, it was very good.', note: 'God looked at His finished work — including you — and called it good.', theme: 'creation' },
    { ref: 'Genesis 2:7', text: 'And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.', note: 'Your very breath is a gift, given on purpose.', theme: 'creation' },
    { ref: 'Genesis 2:18', text: 'And the LORD God said, It is not good that the man should be alone; I will make him an help meet for him.', note: 'God designed us for community, not isolation.', theme: 'creation' },
    { ref: 'Psalm 19:1', text: 'The heavens declare the glory of God; and the firmament sheweth his handywork.', note: 'Creation itself is a constant, silent sermon.', theme: 'creation' },
    { ref: 'Psalm 24:1', text: "The earth is the LORD's, and the fulness thereof; the world, and they that dwell therein.", note: 'Everything you see — and everything you have — belongs to Him first.', theme: 'creation' },
    { ref: 'Psalm 33:6', text: 'By the word of the LORD were the heavens made; and all the host of them by the breath of his mouth.', note: 'Spoken words shaped galaxies — imagine what your words can shape.', theme: 'creation' },
    { ref: 'Psalm 90:2', text: 'Before the mountains were brought forth, or ever thou hadst formed the earth and the world, even from everlasting to everlasting, thou art God.', note: 'Long before mountains existed, God already was.', theme: 'creation' },
    { ref: 'Psalm 104:24', text: 'O LORD, how manifold are thy works! in wisdom hast thou made them all: the earth is full of thy riches.', note: 'Look around today — His fingerprints are everywhere.', theme: 'creation' },
    { ref: 'Psalm 139:14', text: 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.', note: 'You are not an accident; you are a masterpiece.', theme: 'creation' },
    { ref: 'Psalm 148:5', text: 'Let them praise the name of the LORD: for he commanded, and they were created.', note: 'All creation exists to point back to its Maker.', theme: 'creation' },
    { ref: 'Isaiah 40:26', text: 'Lift up your eyes on high, and behold who hath created these things, that bringeth out their host by number: he calleth them all by names.', note: 'The God who names every star also knows your name.', theme: 'creation' },
    { ref: 'Isaiah 40:28', text: 'The everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary.', note: 'When you are exhausted, remember: He never grows tired.', theme: 'creation' },
    { ref: 'Jeremiah 10:12', text: 'He hath made the earth by his power, he hath established the world by his wisdom, and hath stretched out the heavens by his discretion.', note: 'Power, wisdom, and care all went into shaping the world you live in.', theme: 'creation' },
    { ref: 'Colossians 1:16', text: 'For by him were all things created, that are in heaven, and that are in earth, visible and invisible: all things were created by him, and for him.', note: 'You were created not just by Christ, but for Him.', theme: 'creation' },
    { ref: 'Hebrews 11:3', text: 'Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.', note: 'Faith sees the unseen hand behind everything visible.', theme: 'creation' },
    { ref: 'Revelation 4:11', text: 'Thou art worthy, O Lord, to receive glory and honour and power: for thou hast created all things, and for thy pleasure they are and were created.', note: 'You exist for God\'s good pleasure — that includes you.', theme: 'creation' },
    { ref: 'Nehemiah 9:6', text: 'Thou, even thou, art LORD alone; thou hast made heaven, the heaven of heavens, with all their host, the earth, and all things that are therein.', note: 'Nothing exists outside the reach of the One who made it all.', theme: 'creation' },
    { ref: 'Job 38:4', text: 'Where wast thou when I laid the foundations of the earth? declare, if thou hast understanding.', note: 'A humble reminder: God\'s wisdom outreaches ours completely.', theme: 'creation' },
    { ref: 'Genesis 2:3', text: 'And God blessed the seventh day, and sanctified it: because that in it he had rested from all his work which God created and made.', note: 'Rest was built into creation from the very start.', theme: 'creation' },

    // ---------------- Noah (22) ----------------
    { ref: 'Genesis 6:8', text: 'But Noah found grace in the eyes of the LORD.', note: 'Even in a dark generation, one faithful life stood out.', theme: 'noah' },
    { ref: 'Genesis 6:9', text: 'Noah was a just man and perfect in his generations, and Noah walked with God.', note: 'A steady walk with God matters more than a perfect world around you.', theme: 'noah' },
    { ref: 'Genesis 6:14', text: 'Make thee an ark of gopher wood; rooms shalt thou make in the ark, and shalt pitch it within and without with pitch.', note: 'God gives specific instructions — obedience follows the details.', theme: 'noah' },
    { ref: 'Genesis 6:22', text: 'Thus did Noah; according to all that God commanded him, so did he.', note: 'Full obedience, not partial obedience, is the goal.', theme: 'noah' },
    { ref: 'Genesis 7:1', text: 'And the LORD said unto Noah, Come thou and all thy house into the ark; for thee have I seen righteous before me in this generation.', note: 'God\'s call to Noah included his whole household.', theme: 'noah' },
    { ref: 'Genesis 7:16', text: 'And they that went in, went in male and female of all flesh, as God had commanded him: and the LORD shut them in.', note: 'When God closes the door, He is protecting, not punishing.', theme: 'noah' },
    { ref: 'Genesis 8:1', text: 'And God remembered Noah, and every living thing, and all the cattle that was with him in the ark: and God made a wind to pass over the earth, and the waters asswaged.', note: 'Even in the longest storm, God has not forgotten you.', theme: 'noah' },
    { ref: 'Genesis 8:11', text: 'And the dove came in to him in the evening; and, lo, in her mouth was an olive leaf pluckt off: so Noah knew that the waters were abated from the earth.', note: 'A small sign of hope can mean the storm is finally passing.', theme: 'noah' },
    { ref: 'Genesis 8:21', text: 'And the LORD smelled a sweet savour; and the LORD said in his heart, I will not again curse the ground any more for man\'s sake.', note: 'Worship after deliverance is a fitting response to God\'s mercy.', theme: 'noah' },
    { ref: 'Genesis 9:11', text: 'And I will establish my covenant with you; neither shall all flesh be cut off any more by the waters of a flood; neither shall there any more be a flood to destroy the earth.', note: 'God\'s promises are permanent, not temporary.', theme: 'noah' },
    { ref: 'Genesis 9:13', text: 'I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth.', note: 'The rainbow is a sign that God keeps His word.', theme: 'noah' },
    { ref: 'Genesis 9:16', text: 'And the bow shall be in the cloud; and I will look upon it, that I may remember the everlasting covenant between God and every creature.', note: 'God remembers His covenant even when we forget.', theme: 'noah' },
    { ref: 'Hebrews 11:7', text: 'By faith Noah, being warned of God of things not seen as yet, moved with fear, prepared an ark to the saving of his house.', note: 'Faith acts on what God says, before it can be seen.', theme: 'noah' },
    { ref: '2 Peter 2:5', text: 'And spared not the old world, but saved Noah the eighth person, a preacher of righteousness, bringing in the flood upon the world of the ungodly.', note: 'Noah didn\'t just survive the flood — he preached through it.', theme: 'noah' },
    { ref: '1 Peter 3:20', text: 'Which sometime were disobedient, when once the longsuffering of God waited in the days of Noah, while the ark was a preparing, wherein few, that is, eight souls were saved by water.', note: 'God\'s patience gave people time to turn back before the flood came.', theme: 'noah' },
    { ref: 'Isaiah 54:9', text: 'For this is as the waters of Noah unto me: for as I have sworn that the waters of Noah should no more go over the earth, so have I sworn that I would not be wroth with thee.', note: 'God\'s covenant faithfulness reaches far beyond one generation.', theme: 'noah' },
    { ref: 'Psalm 29:10', text: 'The LORD sitteth upon the flood; yea, the LORD sitteth King for ever.', note: 'Even in the flood, God was never off His throne.', theme: 'noah' },
    { ref: '2 Peter 2:9', text: 'The Lord knoweth how to deliver the godly out of temptations, and to reserve the unjust unto the day of judgment to be punished.', note: 'God knows exactly how to rescue those who trust Him.', theme: 'noah' },
    { ref: 'Genesis 9:1', text: 'And God blessed Noah and his sons, and said unto them, Be fruitful, and multiply, and replenish the earth.', note: 'After the flood came a fresh blessing and a fresh start.', theme: 'noah' },
    { ref: 'Genesis 9:9', text: 'And I, behold, I establish my covenant with you, and with your seed after you.', note: 'God\'s promises extend beyond us to those who come after.', theme: 'noah' },
    { ref: 'Genesis 7:23', text: 'And Noah only remained alive, and they that were with him in the ark.', note: 'Obedience carried Noah\'s family safely through the judgment.', theme: 'noah' },
    { ref: 'Matthew 24:37', text: 'But as the days of Noe were, so shall also the coming of the Son of man be.', note: 'Jesus pointed back to Noah\'s day as a lesson in staying ready.', theme: 'noah' },

    // ---------------- Abraham (22) ----------------
    { ref: 'Genesis 12:1', text: 'Now the LORD had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father\'s house, unto a land that I will shew thee.', note: 'Sometimes faith means leaving what is familiar.', theme: 'abraham' },
    { ref: 'Genesis 12:2', text: 'And I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing.', note: 'God\'s blessing is meant to flow through you to others.', theme: 'abraham' },
    { ref: 'Genesis 12:3', text: 'And I will bless them that bless thee, and curse him that curseth thee: and in thee shall all families of the earth be blessed.', note: 'One man\'s obedience became a blessing for the whole earth.', theme: 'abraham' },
    { ref: 'Genesis 12:4', text: 'So Abram departed, as the LORD had spoken unto him; and Lot went with him: and Abram was seventy and five years old when he departed out of Haran.', note: 'It\'s never too late to follow where God leads.', theme: 'abraham' },
    { ref: 'Genesis 15:5', text: 'And he brought him forth abroad, and said, Look now toward heaven, and tell the stars, if thou be able to number them: and he said unto him, So shall thy seed be.', note: 'God\'s promises are often bigger than we can count.', theme: 'abraham' },
    { ref: 'Genesis 15:6', text: 'And he believed in the LORD; and he counted it to him for righteousness.', note: 'Simple trust in God is what He counts as righteousness.', theme: 'abraham' },
    { ref: 'Genesis 17:1', text: 'I am the Almighty God; walk before me, and be thou perfect.', note: 'God introduces Himself before He gives instruction.', theme: 'abraham' },
    { ref: 'Genesis 17:5', text: 'Neither shall thy name any more be called Abram, but thy name shall be Abraham; for a father of many nations have I made thee.', note: 'God gives new names and new identities to those who follow Him.', theme: 'abraham' },
    { ref: 'Genesis 18:14', text: 'Is any thing too hard for the LORD? At the time appointed I will return unto thee, according to the time of life, and Sarah shall have a son.', note: 'Nothing is too difficult for God, no matter how impossible it looks.', theme: 'abraham' },
    { ref: 'Genesis 21:1', text: 'And the LORD visited Sarah as he had said, and the LORD did unto Sarah as he had spoken.', note: 'God keeps His word, even when the wait is long.', theme: 'abraham' },
    { ref: 'Genesis 22:2', text: 'Take now thy son, thine only son Isaac, whom thou lovest, and get thee into the land of Moriah; and offer him there for a burnt offering.', note: 'God sometimes tests what we hold most dear.', theme: 'abraham' },
    { ref: 'Genesis 22:14', text: 'And Abraham called the name of that place Jehovahjireh: as it is said to this day, In the mount of the LORD it shall be seen.', note: 'God provides — often at the exact moment of greatest need.', theme: 'abraham' },
    { ref: 'Genesis 22:17', text: 'That in blessing I will bless thee, and in multiplying I will multiply thy seed as the stars of the heaven, and as the sand which is upon the sea shore.', note: 'Obedience under testing led to an even greater blessing.', theme: 'abraham' },
    { ref: 'Genesis 22:18', text: 'And in thy seed shall all the nations of the earth be blessed; because thou hast obeyed my voice.', note: 'Abraham\'s obedience carried blessing far beyond his own life.', theme: 'abraham' },
    { ref: 'Hebrews 11:8', text: 'By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went.', note: 'Faith obeys before it fully understands the plan.', theme: 'abraham' },
    { ref: 'Hebrews 11:17', text: 'By faith Abraham, when he was tried, offered up Isaac: and he that had received the promises offered up his only begotten son.', note: 'True faith trusts God even when His instructions are hard.', theme: 'abraham' },
    { ref: 'Romans 4:3', text: 'For what saith the scripture? Abraham believed God, and it was counted unto him for righteousness.', note: 'Faith, not works, was credited to Abraham as righteousness.', theme: 'abraham' },
    { ref: 'Galatians 3:6', text: 'Even as Abraham believed God, and it was accounted to him for righteousness.', note: 'The pattern of faith set by Abraham still applies today.', theme: 'abraham' },
    { ref: 'Galatians 3:9', text: 'So then they which be of faith are blessed with faithful Abraham.', note: 'Anyone who trusts God shares in Abraham\'s blessing.', theme: 'abraham' },
    { ref: 'James 2:23', text: 'And the scripture was fulfilled which saith, Abraham believed God, and it was imputed unto him for righteousness: and he was called the Friend of God.', note: 'Faith turned Abraham into something remarkable: a friend of God.', theme: 'abraham' },
    { ref: 'Isaiah 41:8', text: 'But thou, Israel, art my servant, Jacob whom I have chosen, the seed of Abraham my friend.', note: 'God still calls those who trust Him His friends.', theme: 'abraham' },
    { ref: 'Genesis 13:14', text: 'And the LORD said unto Abram, after that Lot was separated from him, Lift up now thine eyes, and look from the place where thou art northward, and southward, and eastward, and westward.', note: 'God often reveals more of His plan after a season of separation.', theme: 'abraham' },

    // ---------------- Exodus (22) ----------------
    { ref: 'Exodus 3:14', text: 'And God said unto Moses, I AM THAT I AM: and he said, Thus shalt thou say unto the children of Israel, I AM hath sent me unto you.', note: 'God\'s name declares His eternal, unchanging presence.', theme: 'exodus' },
    { ref: 'Exodus 3:8', text: 'And I am come down to deliver them out of the hand of the Egyptians, and to bring them up out of that land unto a good land and a large.', note: 'God sees oppression and comes down to deliver.', theme: 'exodus' },
    { ref: 'Exodus 3:12', text: 'And he said, Certainly I will be with thee; and this shall be a token unto thee, that I have sent thee.', note: 'God\'s presence is the promise behind every calling.', theme: 'exodus' },
    { ref: 'Exodus 4:12', text: 'Now therefore go, and I will be with thy mouth, and teach thee what thou shalt say.', note: 'God equips the ones He calls, even when they feel unqualified.', theme: 'exodus' },
    { ref: 'Exodus 6:6', text: 'Wherefore say unto the children of Israel, I am the LORD, and I will bring you out from under the burdens of the Egyptians, and I will rid you out of their bondage.', note: 'God actively works to bring His people out of bondage.', theme: 'exodus' },
    { ref: 'Exodus 12:13', text: 'And the blood shall be to you for a token upon the houses where ye are: and when I see the blood, I will pass over you.', note: 'The blood of the lamb was the sign of protection and mercy.', theme: 'exodus' },
    { ref: 'Exodus 13:21', text: 'And the LORD went before them by day in a pillar of a cloud, to lead them the way; and by night in a pillar of fire, to give them light.', note: 'God leads visibly, day and night, through every season.', theme: 'exodus' },
    { ref: 'Exodus 14:13', text: 'And Moses said unto the people, Fear ye not, stand still, and see the salvation of the LORD, which he will shew to you to day.', note: 'Sometimes the bravest move is to stand still and trust.', theme: 'exodus' },
    { ref: 'Exodus 14:14', text: 'The LORD shall fight for you, and ye shall hold your peace.', note: 'God fights battles that are too big for us to fight alone.', theme: 'exodus' },
    { ref: 'Exodus 15:2', text: 'The LORD is my strength and song, and he is become my salvation: he is my God, and I will prepare him an habitation; my father\'s God, and I will exalt him.', note: 'Deliverance leads naturally into worship.', theme: 'exodus' },
    { ref: 'Exodus 15:11', text: 'Who is like unto thee, O LORD, among the gods? who is like thee, glorious in holiness, fearful in praises, doing wonders?', note: 'No power compares to the wonder-working God of Israel.', theme: 'exodus' },
    { ref: 'Exodus 15:26', text: 'I am the LORD that healeth thee.', note: 'God reveals Himself as the source of healing.', theme: 'exodus' },
    { ref: 'Exodus 16:4', text: 'Then said the LORD unto Moses, Behold, I will rain bread from heaven for you.', note: 'God provides daily bread for daily need.', theme: 'exodus' },
    { ref: 'Exodus 19:5', text: 'Now therefore, if ye will obey my voice indeed, and keep my covenant, then ye shall be a peculiar treasure unto me above all people.', note: 'Obedience flows from being treasured, not the other way around.', theme: 'exodus' },
    { ref: 'Exodus 20:2', text: 'I am the LORD thy God, which have brought thee out of the land of Egypt, out of the house of bondage.', note: 'The commandments begin with a reminder of redemption.', theme: 'exodus' },
    { ref: 'Exodus 20:3', text: 'Thou shalt have no other gods before me.', note: 'First and foremost, God asks for undivided devotion.', theme: 'exodus' },
    { ref: 'Exodus 33:14', text: 'And he said, My presence shall go with thee, and I will give thee rest.', note: 'God\'s presence is what makes the journey bearable.', theme: 'exodus' },
    { ref: 'Exodus 34:6', text: 'The LORD, The LORD God, merciful and gracious, longsuffering, and abundant in goodness and truth.', note: 'This is how God describes His own character: merciful and true.', theme: 'exodus' },
    { ref: 'Deuteronomy 4:20', text: 'But the LORD hath taken you, and brought you forth out of the iron furnace, even out of Egypt, to be unto him a people of inheritance.', note: 'God rescues His people to make them His own.', theme: 'exodus' },
    { ref: 'Psalm 78:52', text: 'But made his own people to go forth like sheep, and guided them in the wilderness like a flock.', note: 'God shepherds His people even through the wilderness.', theme: 'exodus' },
    { ref: 'Exodus 6:7', text: 'And I will take you to me for a people, and I will be to you a God: and ye shall know that I am the LORD your God, which bringeth you out from under the burdens of the Egyptians.', note: 'Redemption is relational — God takes His people as His own.', theme: 'exodus' },
    { ref: 'Exodus 14:21', text: 'And Moses stretched out his hand over the sea; and the LORD caused the sea to go back by a strong east wind all that night, and made the sea dry land, and the waters were divided.', note: 'God can make a way where there seems to be no way at all.', theme: 'exodus' },

    // ---------------- Promised Land (22) ----------------
    { ref: 'Joshua 1:5', text: 'There shall not any man be able to stand before thee all the days of thy life: as I was with Moses, so I will be with thee: I will not fail thee, nor forsake thee.', note: 'God\'s presence transfers from one generation of leadership to the next.', theme: 'promised_land' },
    { ref: 'Joshua 1:6', text: 'Be strong and of a good courage: for unto this people shalt thou divide for an inheritance the land, which I sware unto their fathers to give them.', note: 'Courage is commanded because the promise is certain.', theme: 'promised_land' },
    { ref: 'Joshua 1:7', text: 'Only be thou strong and very courageous, that thou mayest observe to do according to all the law.', note: 'Courage and obedience to God\'s word go hand in hand.', theme: 'promised_land' },
    { ref: 'Joshua 1:8', text: 'This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night.', note: 'Constant meditation on God\'s word shapes a courageous life.', theme: 'promised_land' },
    { ref: 'Joshua 1:9', text: 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.', note: 'Wherever you go today, God goes with you.', theme: 'promised_land' },
    { ref: 'Joshua 3:5', text: 'And Joshua said unto the people, Sanctify yourselves: for to morrow the LORD will do wonders among you.', note: 'Preparing our hearts positions us to see God work.', theme: 'promised_land' },
    { ref: 'Joshua 6:20', text: 'So the people shouted when the priests blew with the trumpets: and the wall fell down flat.', note: 'Obedience, even unusual obedience, can bring down walls.', theme: 'promised_land' },
    { ref: 'Joshua 21:45', text: 'There failed not ought of any good thing which the LORD had spoken unto the house of Israel; all came to pass.', note: 'Not one of God\'s good promises fell to the ground.', theme: 'promised_land' },
    { ref: 'Joshua 23:14', text: 'Not one thing hath failed of all the good things which the LORD your God spake concerning you; all are come to pass unto you, and not one thing hath failed.', note: 'Look back and you\'ll see how faithful God has already been.', theme: 'promised_land' },
    { ref: 'Joshua 24:15', text: 'Choose you this day whom ye will serve... but as for me and my house, we will serve the LORD.', note: 'Every day is a fresh chance to choose whom you\'ll serve.', theme: 'promised_land' },
    { ref: 'Deuteronomy 6:5', text: 'And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.', note: 'Wholehearted love for God is the foundation of everything else.', theme: 'promised_land' },
    { ref: 'Deuteronomy 7:9', text: 'Know therefore that the LORD thy God, he is God, the faithful God, which keepeth covenant and mercy with them that love him.', note: 'God\'s faithfulness is a defining, unshakeable trait.', theme: 'promised_land' },
    { ref: 'Deuteronomy 31:6', text: 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.', note: 'You are never facing your challenges alone.', theme: 'promised_land' },
    { ref: 'Deuteronomy 31:8', text: 'And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed.', note: 'God goes ahead of you into whatever lies next.', theme: 'promised_land' },
    { ref: 'Numbers 13:30', text: 'And Caleb stilled the people before Moses, and said, Let us go up at once, and possess it; for we are well able to overcome it.', note: 'Faith looks at the same facts as fear and sees possibility.', theme: 'promised_land' },
    { ref: 'Numbers 14:8', text: 'If the LORD delight in us, then he will bring us into this land, and give it us; a land which floweth with milk and honey.', note: 'God\'s delight in His people leads Him to bless them richly.', theme: 'promised_land' },
    { ref: 'Deuteronomy 8:7', text: 'For the LORD thy God bringeth thee into a good land, a land of brooks of water, of fountains and depths that spring out of valleys and hills.', note: 'God\'s provision for His people is generous and abundant.', theme: 'promised_land' },
    { ref: 'Deuteronomy 28:2', text: 'And all these blessings shall come on thee, and overtake thee, if thou shalt hearken unto the voice of the LORD thy God.', note: 'Blessing follows a life tuned to listen to God.', theme: 'promised_land' },
    { ref: 'Deuteronomy 34:4', text: 'And the LORD said unto him, This is the land which I sware unto Abraham, unto Isaac, and unto Jacob, saying, I will give it unto thy seed.', note: 'God\'s promises span generations, fulfilled in His own timing.', theme: 'promised_land' },
    { ref: 'Deuteronomy 11:24', text: 'Every place whereon the soles of your feet shall tread shall be yours.', note: 'Faith steps forward into what God has already promised.', theme: 'promised_land' },
    { ref: 'Joshua 24:13', text: 'And I have given you a land for which ye did not labour, and cities which ye built not, and ye dwell in them.', note: 'Much of what we enjoy is grace we did not earn.', theme: 'promised_land' },
    { ref: 'Deuteronomy 1:30', text: 'The LORD your God which goeth before you, he shall fight for you.', note: 'God fights on behalf of those who follow Him forward.', theme: 'promised_land' },

    // ---------------- Kings (22) ----------------
    { ref: '1 Samuel 2:2', text: 'There is none holy as the LORD: for there is none beside thee: neither is there any rock like our God.', note: 'God stands utterly alone in holiness and reliability.', theme: 'kings' },
    { ref: '1 Samuel 3:10', text: 'And the LORD came, and stood, and called as at other times, Samuel, Samuel. Then Samuel answered, Speak; for thy servant heareth.', note: 'A listening heart is ready to hear God\'s call.', theme: 'kings' },
    { ref: '1 Samuel 16:7', text: 'For the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart.', note: 'God values what\'s inside far more than outward appearance.', theme: 'kings' },
    { ref: '1 Samuel 17:45', text: 'Then said David to the Philistine, Thou comest to me with a sword, and with a spear, and with a shield: but I come to thee in the name of the LORD of hosts.', note: 'Faith brings a different kind of weapon into any battle.', theme: 'kings' },
    { ref: '1 Samuel 17:47', text: 'The battle is the LORD\'s, and he will give you into our hands.', note: 'Every real victory ultimately belongs to God.', theme: 'kings' },
    { ref: '2 Samuel 7:16', text: 'And thine house and thy kingdom shall be established for ever before thee: thy throne shall be established for ever.', note: 'God\'s promise to David pointed toward an everlasting kingdom.', theme: 'kings' },
    { ref: '2 Samuel 22:2', text: 'And he said, The LORD is my rock, and my fortress, and my deliverer.', note: 'David\'s song of victory begins by naming God as his safety.', theme: 'kings' },
    { ref: '1 Kings 3:9', text: 'Give therefore thy servant an understanding heart to judge thy people, that I may discern between good and bad.', note: 'Solomon\'s first request was wisdom, not wealth.', theme: 'kings' },
    { ref: '1 Kings 8:23', text: 'LORD God of Israel, there is no God like thee, in heaven above, or on earth beneath, who keepest covenant and mercy with thy servants.', note: 'No other power keeps promises like the God of Israel.', theme: 'kings' },
    { ref: '1 Kings 8:57', text: 'The LORD our God be with us, as he was with our fathers: let him not leave us, nor forsake us.', note: 'The same God who helped past generations is with us today.', theme: 'kings' },
    { ref: '2 Kings 6:16', text: 'And he answered, Fear not: for they that be with us are more than they that be with them.', note: 'There is more help on your side than you can currently see.', theme: 'kings' },
    { ref: '1 Chronicles 16:11', text: 'Seek the LORD and his strength, seek his face continually.', note: 'A continual seeking, not a one-time search, keeps us close to God.', theme: 'kings' },
    { ref: '1 Chronicles 16:34', text: 'O give thanks unto the LORD; for he is good; for his mercy endureth for ever.', note: 'Gratitude is the natural response to God\'s enduring mercy.', theme: 'kings' },
    { ref: '1 Chronicles 29:11', text: 'Thine, O LORD, is the greatness, and the power, and the glory, and the victory, and the majesty: for all that is in the heaven and in the earth is thine.', note: 'Every kingdom, big or small, belongs ultimately to God.', theme: 'kings' },
    { ref: '2 Chronicles 7:14', text: 'If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven.', note: 'Humility and prayer open the door to God\'s healing.', theme: 'kings' },
    { ref: '2 Chronicles 16:9', text: 'For the eyes of the LORD run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is perfect toward him.', note: 'God is actively searching for hearts fully devoted to Him.', theme: 'kings' },
    { ref: '2 Chronicles 20:15', text: 'Be not afraid nor dismayed by reason of this great multitude; for the battle is not yours, but God\'s.', note: 'Some battles are meant to be given over to God entirely.', theme: 'kings' },
    { ref: 'Proverbs 3:5', text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', note: 'Trusting God fully means letting go of relying only on yourself.', theme: 'kings' },
    { ref: 'Proverbs 16:3', text: 'Commit thy works unto the LORD, and thy thoughts shall be established.', note: 'Handing your plans to God brings steadiness of mind.', theme: 'kings' },
    { ref: 'Proverbs 22:1', text: 'A good name is rather to be chosen than great riches, and loving favour rather than silver and gold.', note: 'Character and integrity outweigh wealth every time.', theme: 'kings' },
    { ref: '1 Samuel 15:22', text: 'Behold, to obey is better than sacrifice, and to hearken than the fat of rams.', note: 'God values obedience far above outward religious ritual.', theme: 'kings' },
    { ref: '1 Kings 19:12', text: 'And after the fire a still small voice.', note: 'God often speaks in the quiet, not just the dramatic.', theme: 'kings' },

    // ---------------- Prophets (21) ----------------
    { ref: 'Isaiah 1:18', text: 'Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow.', note: 'God offers cleansing, no matter how deep the stain.', theme: 'prophets' },
    { ref: 'Isaiah 6:8', text: 'Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me.', note: 'A willing heart answers God\'s call before knowing the full plan.', theme: 'prophets' },
    { ref: 'Isaiah 9:6', text: 'For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.', note: 'Isaiah foresaw the coming of Christ centuries in advance.', theme: 'prophets' },
    { ref: 'Isaiah 26:3', text: 'Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.', note: 'Peace comes from where our thoughts are fixed.', theme: 'prophets' },
    { ref: 'Isaiah 40:31', text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.', note: 'Waiting on God is not wasted time — it renews our strength.', theme: 'prophets' },
    { ref: 'Isaiah 41:10', text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.', note: 'God\'s presence dissolves the reason to be afraid.', theme: 'prophets' },
    { ref: 'Isaiah 43:2', text: 'When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.', note: 'God promises presence through hardship, not exemption from it.', theme: 'prophets' },
    { ref: 'Isaiah 53:5', text: 'But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.', note: 'Isaiah prophesied the suffering that would bring our healing.', theme: 'prophets' },
    { ref: 'Isaiah 61:1', text: 'The Spirit of the Lord GOD is upon me; because the LORD hath anointed me to preach good tidings unto the meek.', note: 'Good news for the brokenhearted was promised long before it arrived.', theme: 'prophets' },
    { ref: 'Jeremiah 1:5', text: 'Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee.', note: 'God knew you and had purpose for you before you were born.', theme: 'prophets' },
    { ref: 'Jeremiah 17:7', text: 'Blessed is the man that trusteth in the LORD, and whose hope the LORD is.', note: 'A trusting life is a blessed life.', theme: 'prophets' },
    { ref: 'Jeremiah 29:11', text: 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.', note: 'God\'s plans for you are good, even when you can\'t see them yet.', theme: 'prophets' },
    { ref: 'Jeremiah 31:3', text: 'I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee.', note: 'God\'s love for you has no expiration date.', theme: 'prophets' },
    { ref: 'Jeremiah 33:3', text: 'Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.', note: 'God invites us to call on Him and promises to answer.', theme: 'prophets' },
    { ref: 'Ezekiel 36:26', text: 'A new heart also will I give you, and a new spirit will I put within you.', note: 'God offers transformation from the inside out.', theme: 'prophets' },
    { ref: 'Daniel 3:17', text: 'Our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of thine hand, O king.', note: 'Confidence in God\'s power steadies us in the hottest trials.', theme: 'prophets' },
    { ref: 'Daniel 6:22', text: 'My God hath sent his angel, and hath shut the lions\' mouths, that they have not hurt me.', note: 'God can shut every mouth that threatens His faithful ones.', theme: 'prophets' },
    { ref: 'Hosea 6:6', text: 'For I desired mercy, and not sacrifice; and the knowledge of God more than burnt offerings.', note: 'God wants a real relationship more than religious performance.', theme: 'prophets' },
    { ref: 'Joel 2:25', text: 'And I will restore to you the years that the locust hath eaten.', note: 'God can restore what seemed permanently lost.', theme: 'prophets' },
    { ref: 'Micah 6:8', text: 'What doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?', note: 'A simple, clear summary of what a godly life looks like.', theme: 'prophets' },
    { ref: 'Zephaniah 3:17', text: 'The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy.', note: 'God doesn\'t just tolerate you — He rejoices over you.', theme: 'prophets' },

    // ---------------- Birth of Christ (21) ----------------
    { ref: 'Isaiah 7:14', text: 'Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel.', note: 'God with us — promised centuries before He arrived.', theme: 'nativity' },
    { ref: 'Micah 5:2', text: 'But thou, Bethlehem Ephratah... out of thee shall he come forth unto me that is to be ruler in Israel.', note: 'Even the small town of His birth was foretold.', theme: 'nativity' },
    { ref: 'Matthew 1:21', text: 'And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins.', note: 'His name itself carries His mission: to save.', theme: 'nativity' },
    { ref: 'Matthew 1:23', text: 'Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us.', note: 'Christmas is, at its heart, God choosing to be with us.', theme: 'nativity' },
    { ref: 'Matthew 2:10', text: 'When they saw the star, they rejoiced with exceeding great joy.', note: 'Finding Jesus is cause for overflowing joy.', theme: 'nativity' },
    { ref: 'Matthew 2:11', text: 'And when they were come into the house, they saw the young child with Mary his mother, and fell down, and worshipped him.', note: 'The wise men\'s first response to Jesus was worship.', theme: 'nativity' },
    { ref: 'Luke 1:28', text: 'And the angel came in unto her, and said, Hail, thou that art highly favoured, the Lord is with thee.', note: 'Mary was chosen and favored for an extraordinary calling.', theme: 'nativity' },
    { ref: 'Luke 1:30', text: 'And the angel said unto her, Fear not, Mary: for thou hast found favour with God.', note: 'God\'s favor often begins with a word of comfort, not fear.', theme: 'nativity' },
    { ref: 'Luke 1:35', text: 'The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee: therefore also that holy thing which shall be born of thee shall be called the Son of God.', note: 'The birth of Jesus was a miracle from start to finish.', theme: 'nativity' },
    { ref: 'Luke 1:37', text: 'For with God nothing shall be impossible.', note: 'The virgin birth reminds us: nothing is impossible for God.', theme: 'nativity' },
    { ref: 'Luke 1:46', text: 'And Mary said, My soul doth magnify the Lord.', note: 'Mary\'s response to God\'s calling was worship, not worry.', theme: 'nativity' },
    { ref: 'Luke 2:7', text: 'And she brought forth her firstborn son, and wrapped him in swaddling clothes, and laid him in a manger; because there was no room for them in the inn.', note: 'The King of Kings began His life in humble surroundings.', theme: 'nativity' },
    { ref: 'Luke 2:10', text: 'And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people.', note: 'The good news of Christmas is meant for absolutely everyone.', theme: 'nativity' },
    { ref: 'Luke 2:11', text: 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.', note: 'A Savior was born — for you, specifically.', theme: 'nativity' },
    { ref: 'Luke 2:14', text: 'Glory to God in the highest, and on earth peace, good will toward men.', note: 'Heaven celebrated the arrival of peace on earth.', theme: 'nativity' },
    { ref: 'Luke 2:19', text: 'But Mary kept all these things, and pondered them in her heart.', note: 'Some of God\'s work in us is meant to be quietly treasured.', theme: 'nativity' },
    { ref: 'John 1:14', text: 'And the Word was made flesh, and dwelt among us, and we beheld his glory, the glory as of the only begotten of the Father, full of grace and truth.', note: 'God stepped into human history, full of grace and truth.', theme: 'nativity' },
    { ref: 'Galatians 4:4', text: 'But when the fulness of the time was come, God sent forth his Son, made of a woman, made under the law.', note: 'Christ arrived at exactly the right moment in history.', theme: 'nativity' },
    { ref: 'Titus 2:11', text: 'For the grace of God that bringeth salvation hath appeared to all men.', note: 'Grace itself appeared, visible and available to all.', theme: 'nativity' },
    { ref: '1 Timothy 3:16', text: 'God was manifest in the flesh, justified in the Spirit, seen of angels, preached unto the Gentiles, believed on in the world, received up into glory.', note: 'The mystery of Christmas: God made visible.', theme: 'nativity' },
    { ref: 'Philippians 2:7', text: 'But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men.', note: 'Jesus willingly gave up glory to take on our humanity.', theme: 'nativity' },

    // ---------------- Miracles (21) ----------------
    { ref: 'Matthew 8:3', text: 'And Jesus put forth his hand, and touched him, saying, I will; be thou clean. And immediately his leprosy was cleansed.', note: 'One touch from Jesus was enough to heal completely.', theme: 'miracles' },
    { ref: 'Matthew 9:22', text: 'But Jesus turned him about, and when he saw her, he said, Daughter, be of good comfort; thy faith hath made thee whole.', note: 'Faith reaching toward Jesus brought healing and comfort.', theme: 'miracles' },
    { ref: 'Matthew 14:19', text: 'And he took the five loaves, and the two fishes, and looking up to heaven, he blessed, and brake, and gave the loaves to his disciples.', note: 'A small offering, blessed by Jesus, became more than enough.', theme: 'miracles' },
    { ref: 'Matthew 14:29', text: 'And he said, Come. And when Peter was come down out of the ship, he walked on the water, to go to Jesus.', note: 'Stepping out toward Jesus can carry you beyond what seems possible.', theme: 'miracles' },
    { ref: 'Mark 2:5', text: 'When Jesus saw their faith, he said unto the sick of the palsy, Son, thy sins be forgiven thee.', note: 'Jesus saw not just the need, but the faith behind it.', theme: 'miracles' },
    { ref: 'Mark 4:39', text: 'And he arose, and rebuked the wind, and said unto the sea, Peace, be still. And the wind ceased, and there was a great calm.', note: 'Jesus speaks peace into the fiercest storms.', theme: 'miracles' },
    { ref: 'Mark 5:34', text: 'And he said unto her, Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague.', note: 'Jesus sends the healed away in peace, not just health.', theme: 'miracles' },
    { ref: 'Mark 5:41', text: 'And he took the damsel by the hand, and said unto her, Talitha cumi... Damsel, I say unto thee, arise.', note: 'Jesus\'s words have power even over death.', theme: 'miracles' },
    { ref: 'Luke 5:5', text: 'And Simon answering said unto him, Master, we have toiled all the night, and have taken nothing: nevertheless at thy word I will let down the net.', note: 'Obedience to Jesus\'s word, even after failure, brings breakthrough.', theme: 'miracles' },
    { ref: 'Luke 7:14', text: 'And he came and touched the bier: and they that bare him stood still. And he said, Young man, I say unto thee, Arise.', note: 'Jesus interrupts even a funeral procession with new life.', theme: 'miracles' },
    { ref: 'Luke 8:50', text: 'But when Jesus heard it, he answered him, saying, Fear not: believe only, and she shall be made whole.', note: 'In the face of devastating news, Jesus calls us to keep believing.', theme: 'miracles' },
    { ref: 'John 2:11', text: 'This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him.', note: 'His first miracle revealed His glory and grew His disciples\' faith.', theme: 'miracles' },
    { ref: 'John 5:8', text: 'Jesus saith unto him, Rise, take up thy bed, and walk.', note: 'A simple command from Jesus was enough to restore strength.', theme: 'miracles' },
    { ref: 'John 6:11', text: 'And Jesus took the loaves; and when he had given thanks, he distributed to the disciples, and the disciples to them that were set down.', note: 'Gratitude preceded the miracle of multiplication.', theme: 'miracles' },
    { ref: 'John 9:25', text: 'One thing I know, that, whereas I was blind, now I see.', note: 'Personal testimony is powerful, even without all the answers.', theme: 'miracles' },
    { ref: 'John 11:25', text: 'Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.', note: 'Jesus doesn\'t just perform miracles — He is the miracle of life itself.', theme: 'miracles' },
    { ref: 'John 11:43', text: 'And when he thus had spoken, he cried with a loud voice, Lazarus, come forth.', note: 'Jesus called a dead man back to life with just His voice.', theme: 'miracles' },
    { ref: 'John 20:29', text: 'Jesus saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed.', note: 'Faith without seeing is called especially blessed.', theme: 'miracles' },
    { ref: 'Matthew 17:20', text: 'If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.', note: 'Even tiny faith can move mountains.', theme: 'miracles' },
    { ref: 'Mark 9:23', text: 'Jesus said unto him, If thou canst believe, all things are possible to him that believeth.', note: 'Belief opens the door to what God can do.', theme: 'miracles' },
    { ref: 'Matthew 19:26', text: 'But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible.', note: 'What\'s impossible for us is never impossible for God.', theme: 'miracles' },

    // ---------------- Cross (21) ----------------
    { ref: 'Matthew 26:39', text: 'O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt.', note: 'Jesus modeled surrender even in His deepest anguish.', theme: 'cross' },
    { ref: 'Matthew 27:46', text: 'My God, my God, why hast thou forsaken me?', note: 'Jesus bore even the pain of separation from the Father for us.', theme: 'cross' },
    { ref: 'Matthew 27:50', text: 'Jesus, when he had cried again with a loud voice, yielded up the ghost.', note: 'Jesus willingly laid down His life; it was not taken from Him.', theme: 'cross' },
    { ref: 'Luke 23:34', text: 'Then said Jesus, Father, forgive them; for they know not what they do.', note: 'Even from the cross, Jesus extended forgiveness.', theme: 'cross' },
    { ref: 'Luke 23:43', text: 'And Jesus said unto him, Verily I say unto thee, To day shalt thou be with me in paradise.', note: 'Even in His final hours, Jesus offered hope to a dying thief.', theme: 'cross' },
    { ref: 'Luke 23:46', text: 'And when Jesus had cried with a loud voice, he said, Father, into thy hands I commend my spirit.', note: 'Jesus\'s last words were an act of complete trust.', theme: 'cross' },
    { ref: 'John 3:16', text: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.', note: 'The cross is the ultimate proof of God\'s love for the world.', theme: 'cross' },
    { ref: 'John 15:13', text: 'Greater love hath no man than this, that a man lay down his life for his friends.', note: 'Jesus defined love by His willingness to lay down His life.', theme: 'cross' },
    { ref: 'John 19:30', text: 'When Jesus therefore had received the vinegar, he said, It is finished: and he bowed his head, and gave up the ghost.', note: 'The work of redemption was completed at the cross.', theme: 'cross' },
    { ref: 'Isaiah 53:6', text: 'All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him the iniquity of us all.', note: 'Our wandering was answered by His willingness to bear it all.', theme: 'cross' },
    { ref: 'Romans 5:8', text: 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.', note: 'God\'s love reached us before we ever deserved it.', theme: 'cross' },
    { ref: '1 Corinthians 1:18', text: 'For the preaching of the cross is to them that perish foolishness; but unto us which are saved it is the power of God.', note: 'What looks foolish to the world is, in truth, God\'s power.', theme: 'cross' },
    { ref: '2 Corinthians 5:21', text: 'For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.', note: 'A great exchange happened at the cross: our sin for His righteousness.', theme: 'cross' },
    { ref: 'Galatians 2:20', text: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me.', note: 'The cross changes not just our future but our identity now.', theme: 'cross' },
    { ref: 'Galatians 3:13', text: 'Christ hath redeemed us from the curse of the law, being made a curse for us.', note: 'Jesus took the curse so we could receive the blessing.', theme: 'cross' },
    { ref: 'Philippians 2:8', text: 'And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross.', note: 'The cross was the ultimate act of humble obedience.', theme: 'cross' },
    { ref: '1 Peter 2:24', text: 'Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed.', note: 'His wounds became the source of our healing.', theme: 'cross' },
    { ref: '1 Peter 3:18', text: 'For Christ also hath once suffered for sins, the just for the unjust, that he might bring us to God.', note: 'The cross exists to bring us near to God.', theme: 'cross' },
    { ref: 'Hebrews 12:2', text: 'Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame.', note: 'Joy set before Him gave Jesus strength to endure the cross.', theme: 'cross' },
    { ref: 'Colossians 2:14', text: 'Blotting out the handwriting of ordinances that was against us, which was contrary to us, and took it out of the way, nailing it to his cross.', note: 'Every debt against us was nailed to the cross with Him.', theme: 'cross' },
    { ref: 'Romans 6:23', text: 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.', note: 'What we earned was death; what we received is life, as a gift.', theme: 'cross' },

    // ---------------- Resurrection (21) ----------------
    { ref: 'Matthew 28:6', text: 'He is not here: for he is risen, as he said. Come, see the place where the Lord lay.', note: 'The empty tomb is the heart of the good news.', theme: 'resurrection' },
    { ref: 'Matthew 28:7', text: 'And go quickly, and tell his disciples that he is risen from the dead.', note: 'The resurrection is news meant to be shared quickly and widely.', theme: 'resurrection' },
    { ref: 'Matthew 28:20', text: 'And, lo, I am with you alway, even unto the end of the world.', note: 'The risen Jesus promises His presence forever.', theme: 'resurrection' },
    { ref: 'Mark 16:6', text: 'And he saith unto them, Be not affrighted: Ye seek Jesus of Nazareth, which was crucified: he is risen; he is not here.', note: 'The angel\'s message turned fear into astonishing joy.', theme: 'resurrection' },
    { ref: 'Luke 24:6', text: 'He is not here, but is risen: remember how he spake unto you when he was yet in Galilee.', note: 'The resurrection fulfilled exactly what Jesus had promised.', theme: 'resurrection' },
    { ref: 'Luke 24:34', text: 'Saying, The Lord is risen indeed, and hath appeared to Simon.', note: 'Word of the resurrection spread quickly among the disciples.', theme: 'resurrection' },
    { ref: 'John 11:25', text: 'Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.', note: 'Jesus doesn\'t just grant resurrection — He is the resurrection.', theme: 'resurrection' },
    { ref: 'John 20:16', text: 'Jesus saith unto her, Mary. She turned herself, and saith unto him, Rabboni; which is to say, Master.', note: 'The risen Jesus calls each of us by name.', theme: 'resurrection' },
    { ref: 'John 20:17', text: 'Jesus saith unto her, Touch me not; for I am not yet ascended to my Father: but go to my brethren, and say unto them, I ascend unto my Father, and your Father.', note: 'Through the resurrection, His Father became our Father too.', theme: 'resurrection' },
    { ref: 'John 20:19', text: 'Then the same day at evening... came Jesus and stood in the midst, and saith unto them, Peace be unto you.', note: 'The risen Jesus greets His fearful followers with peace.', theme: 'resurrection' },
    { ref: 'John 20:28', text: 'And Thomas answered and said unto him, My Lord and my God.', note: 'Encountering the risen Jesus turns doubt into worship.', theme: 'resurrection' },
    { ref: 'Acts 2:24', text: 'Whom God hath raised up, having loosed the pains of death: because it was not possible that he should be holden of it.', note: 'Death had no power to hold the Author of life.', theme: 'resurrection' },
    { ref: 'Acts 2:32', text: 'This Jesus hath God raised up, whereof we all are witnesses.', note: 'The resurrection is a historical claim backed by eyewitnesses.', theme: 'resurrection' },
    { ref: 'Romans 1:4', text: 'And declared to be the Son of God with power, according to the spirit of holiness, by the resurrection from the dead.', note: 'The resurrection is God\'s declaration of who Jesus truly is.', theme: 'resurrection' },
    { ref: 'Romans 6:4', text: 'Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead... we also should walk in newness of life.', note: 'His resurrection makes a new kind of life possible for us.', theme: 'resurrection' },
    { ref: 'Romans 8:11', text: 'But if the Spirit of him that raised up Jesus from the dead dwell in you, he... shall also quicken your mortal bodies.', note: 'The same power that raised Jesus lives in believers today.', theme: 'resurrection' },
    { ref: '1 Corinthians 15:20', text: 'But now is Christ risen from the dead, and become the firstfruits of them that slept.', note: 'His resurrection guarantees ours is coming too.', theme: 'resurrection' },
    { ref: '1 Corinthians 15:55', text: 'O death, where is thy sting? O grave, where is thy victory?', note: 'The resurrection strips death of its final power.', theme: 'resurrection' },
    { ref: '1 Corinthians 15:57', text: 'But thanks be to God, which giveth us the victory through our Lord Jesus Christ.', note: 'Victory over death and sin comes as a gift, through Christ.', theme: 'resurrection' },
    { ref: '2 Timothy 2:8', text: 'Remember that Jesus Christ of the seed of David was raised from the dead according to my gospel.', note: 'The resurrection is the very center of the gospel message.', theme: 'resurrection' },
    { ref: '1 Peter 1:3', text: 'Blessed be the God and Father of our Lord Jesus Christ, which... hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead.', note: 'The resurrection is the ground of a living, unshakeable hope.', theme: 'resurrection' },

    // ---------------- Acts (21) ----------------
    { ref: 'Acts 1:8', text: 'But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me... unto the uttermost part of the earth.', note: 'The Spirit\'s power turns ordinary believers into bold witnesses.', theme: 'acts' },
    { ref: 'Acts 2:4', text: 'And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.', note: 'Pentecost marked the birth of the church, filled with the Spirit.', theme: 'acts' },
    { ref: 'Acts 2:38', text: 'Then Peter said unto them, Repent, and be baptized every one of you... and ye shall receive the gift of the Holy Ghost.', note: 'Repentance opens the door to receiving the Spirit.', theme: 'acts' },
    { ref: 'Acts 2:42', text: 'And they continued stedfastly in the apostles\' doctrine and fellowship, and in breaking of bread, and in prayers.', note: 'The early church was built on teaching, community, and prayer.', theme: 'acts' },
    { ref: 'Acts 2:44', text: 'And all that believed were together, and had all things common.', note: 'Generosity marked the earliest community of believers.', theme: 'acts' },
    { ref: 'Acts 4:12', text: 'Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.', note: 'The apostles preached one name as the source of salvation: Jesus.', theme: 'acts' },
    { ref: 'Acts 4:31', text: 'And when they had prayed... they were all filled with the Holy Ghost, and they spake the word of God with boldness.', note: 'Prayer preceded boldness in the early church.', theme: 'acts' },
    { ref: 'Acts 4:32', text: 'And the multitude of them that believed were of one heart and of one soul.', note: 'Unity of heart marked the early believers.', theme: 'acts' },
    { ref: 'Acts 5:29', text: 'Then Peter and the other apostles answered and said, We ought to obey God rather than men.', note: 'Faithfulness to God sometimes costs approval from people.', theme: 'acts' },
    { ref: 'Acts 9:15', text: 'But the Lord said unto him, Go thy way: for he is a chosen vessel unto me, to bear my name before the Gentiles.', note: 'God can transform even the fiercest opponent into a chosen messenger.', theme: 'acts' },
    { ref: 'Acts 10:34', text: 'Then Peter opened his mouth, and said, Of a truth I perceive that God is no respecter of persons.', note: 'The gospel breaks down every wall of favoritism.', theme: 'acts' },
    { ref: 'Acts 12:5', text: 'Peter therefore was kept in prison: but prayer was made without ceasing of the church unto God for him.', note: 'A praying church became the instrument of Peter\'s deliverance.', theme: 'acts' },
    { ref: 'Acts 16:25', text: 'And at midnight Paul and Silas prayed, and sang praises unto God: and the prisoners heard them.', note: 'Praise can rise even from the darkest prison cell.', theme: 'acts' },
    { ref: 'Acts 16:31', text: 'And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house.', note: 'Salvation is offered simply through faith in Jesus.', theme: 'acts' },
    { ref: 'Acts 17:11', text: 'These were more noble than those in Thessalonica, in that they received the word with all readiness of mind, and searched the scriptures daily.', note: 'A noble heart tests every teaching against Scripture.', theme: 'acts' },
    { ref: 'Acts 17:28', text: 'For in him we live, and move, and have our being.', note: 'Our very existence is sustained moment by moment in God.', theme: 'acts' },
    { ref: 'Acts 20:24', text: 'But none of these things move me, neither count I my life dear unto myself, so that I might finish my course with joy.', note: 'Paul measured his life by finishing well, not by comfort.', theme: 'acts' },
    { ref: 'Acts 20:35', text: 'It is more blessed to give than to receive.', note: 'Generosity brings a deeper blessing than receiving ever does.', theme: 'acts' },
    { ref: 'Acts 26:18', text: 'To open their eyes, and to turn them from darkness to light, and from the power of Satan unto God.', note: 'The gospel moves people from darkness into light.', theme: 'acts' },
    { ref: 'Acts 28:31', text: 'Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him.', note: 'Even under guard, Paul preached with unstoppable confidence.', theme: 'acts' },
    { ref: 'Acts 9:4', text: 'And he fell to the earth, and heard a voice saying unto him, Saul, Saul, why persecutest thou me?', note: 'God can interrupt anyone\'s path, no matter how set against Him.', theme: 'acts' },

    // ---------------- Missionary Journeys (21) ----------------
    { ref: 'Romans 1:16', text: 'For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth.', note: 'The gospel carries real power, wherever it is proclaimed.', theme: 'missionary' },
    { ref: 'Romans 10:14', text: 'How then shall they call on him in whom they have not believed? and how shall they believe in him of whom they have not heard?', note: 'Sharing the gospel is essential for others to hear and believe.', theme: 'missionary' },
    { ref: 'Romans 10:17', text: 'So then faith cometh by hearing, and hearing by the word of God.', note: 'Faith grows as God\'s word is heard and received.', theme: 'missionary' },
    { ref: '1 Corinthians 9:22', text: 'I am made all things to all men, that I might by all means save some.', note: 'Paul adapted his approach without ever compromising his message.', theme: 'missionary' },
    { ref: '2 Corinthians 4:8', text: 'We are troubled on every side, yet not distressed; we are perplexed, but not in despair.', note: 'Hardship on a mission never has to mean despair.', theme: 'missionary' },
    { ref: '2 Corinthians 5:17', text: 'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.', note: 'The gospel Paul carried made people entirely new.', theme: 'missionary' },
    { ref: '2 Corinthians 5:20', text: 'Now then we are ambassadors for Christ, as though God did beseech you by us: we pray you in Christ\'s stead, be ye reconciled to God.', note: 'Every believer carries the calling of an ambassador.', theme: 'missionary' },
    { ref: '2 Corinthians 12:9', text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.', note: 'God\'s strength shows up most clearly in our weakest moments.', theme: 'missionary' },
    { ref: 'Galatians 6:9', text: 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.', note: 'Perseverance in doing good always leads to a harvest.', theme: 'missionary' },
    { ref: 'Ephesians 6:19', text: 'And for me, that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel.', note: 'Even Paul asked for prayer to speak boldly.', theme: 'missionary' },
    { ref: 'Philippians 1:21', text: 'For to me to live is Christ, and to die is gain.', note: 'A life fully surrendered has nothing left to fear.', theme: 'missionary' },
    { ref: 'Philippians 1:6', text: 'Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.', note: 'God finishes what He starts in every believer.', theme: 'missionary' },
    { ref: 'Philippians 4:11', text: 'Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content.', note: 'Contentment is a learned strength, not a natural circumstance.', theme: 'missionary' },
    { ref: 'Philippians 4:13', text: 'I can do all things through Christ which strengtheneth me.', note: 'Christ\'s strength makes even the hardest calling possible.', theme: 'missionary' },
    { ref: 'Philippians 4:19', text: 'But my God shall supply all your need according to his riches in glory by Christ Jesus.', note: 'God\'s supply matches the riches of His glory, not our lack.', theme: 'missionary' },
    { ref: 'Colossians 1:28', text: 'Whom we preach, warning every man, and teaching every man in all wisdom; that we may present every man perfect in Christ Jesus.', note: 'The goal of ministry is maturity in Christ for everyone reached.', theme: 'missionary' },
    { ref: '1 Thessalonians 5:16', text: 'Rejoice evermore.', note: 'Joy is meant to be a constant, not just an occasional visitor.', theme: 'missionary' },
    { ref: '2 Timothy 1:7', text: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', note: 'God equips His messengers with power, love, and clarity, not fear.', theme: 'missionary' },
    { ref: '2 Timothy 4:7', text: 'I have fought a good fight, I have finished my course, I have kept the faith.', note: 'Paul\'s life closed with the satisfaction of having finished well.', theme: 'missionary' },
    { ref: '2 Timothy 4:17', text: 'Notwithstanding the Lord stood with me, and strengthened me; that by me the preaching might be fully known.', note: 'God stands with His messengers even in the loneliest moments.', theme: 'missionary' },
    { ref: 'Acts 13:2', text: 'As they ministered to the Lord, and fasted, the Holy Ghost said, Separate me Barnabas and Saul for the work whereunto I have called them.', note: 'Missionary calling was confirmed in a season of worship and fasting.', theme: 'missionary' },

    // ---------------- Revelation (21) ----------------
    { ref: 'Revelation 1:8', text: 'I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty.', note: 'God stands at both the beginning and the end of all things.', theme: 'revelation' },
    { ref: 'Revelation 1:17', text: 'And when I saw him, I fell at his feet as dead. And he laid his right hand upon me, saying unto me, Fear not; I am the first and the last.', note: 'Even in overwhelming glory, Jesus\'s first word is comfort.', theme: 'revelation' },
    { ref: 'Revelation 2:10', text: 'Be thou faithful unto death, and I will give thee a crown of life.', note: 'Faithfulness, even under pressure, leads to lasting reward.', theme: 'revelation' },
    { ref: 'Revelation 3:20', text: 'Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him.', note: 'Jesus patiently waits and knocks, ready to enter wherever He\'s welcomed.', theme: 'revelation' },
    { ref: 'Revelation 4:8', text: 'Holy, holy, holy, Lord God Almighty, which was, and is, and is to come.', note: 'Heaven\'s worship centers on the holiness of God.', theme: 'revelation' },
    { ref: 'Revelation 5:12', text: 'Worthy is the Lamb that was slain to receive power, and riches, and wisdom, and strength, and honour, and glory, and blessing.', note: 'The slain Lamb is declared worthy of all praise.', theme: 'revelation' },
    { ref: 'Revelation 7:9', text: 'A great multitude, which no man could number, of all nations, and kindreds, and people, and tongues, stood before the throne.', note: 'God\'s family will span every nation, tribe, and tongue.', theme: 'revelation' },
    { ref: 'Revelation 12:11', text: 'And they overcame him by the blood of the Lamb, and by the word of their testimony.', note: 'Victory comes through Christ\'s blood and a faithful testimony.', theme: 'revelation' },
    { ref: 'Revelation 19:6', text: 'Alleluia: for the Lord God omnipotent reigneth.', note: 'The final word of history is that God reigns.', theme: 'revelation' },
    { ref: 'Revelation 19:16', text: 'And he hath on his vesture and on his thigh a name written, KING OF KINGS, AND LORD OF LORDS.', note: 'Every earthly kingdom bows before the true King of Kings.', theme: 'revelation' },
    { ref: 'Revelation 20:6', text: 'Blessed and holy is he that hath part in the first resurrection.', note: 'Sharing in Christ\'s resurrection is called a blessing.', theme: 'revelation' },
    { ref: 'Revelation 21:1', text: 'And I saw a new heaven and a new earth: for the first heaven and the first earth were passed away.', note: 'God\'s story ends with everything made new.', theme: 'revelation' },
    { ref: 'Revelation 21:3', text: 'Behold, the tabernacle of God is with men, and he will dwell with them, and they shall be his people, and God himself shall be with them, and be their God.', note: 'The end of the story is God dwelling face-to-face with His people.', theme: 'revelation' },
    { ref: 'Revelation 21:4', text: 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain.', note: 'Every tear, every sorrow, will one day be wiped away for good.', theme: 'revelation' },
    { ref: 'Revelation 21:5', text: 'And he that sat upon the throne said, Behold, I make all things new.', note: 'God\'s final work is not destruction, but renewal.', theme: 'revelation' },
    { ref: 'Revelation 21:6', text: 'I will give unto him that is athirst of the fountain of the water of life freely.', note: 'The deepest thirst of the soul is freely satisfied in God.', theme: 'revelation' },
    { ref: 'Revelation 22:1', text: 'And he shewed me a pure river of water of life, clear as crystal, proceeding out of the throne of God and of the Lamb.', note: 'Life itself flows from the throne of God.', theme: 'revelation' },
    { ref: 'Revelation 22:12', text: 'And, behold, I come quickly; and my reward is with me, to give every man according as his work shall be.', note: 'Christ\'s return comes with reward for faithful work.', theme: 'revelation' },
    { ref: 'Revelation 22:13', text: 'I am Alpha and Omega, the beginning and the end, the first and the last.', note: 'The story that began with God will also end with God.', theme: 'revelation' },
    { ref: 'Revelation 22:17', text: 'And the Spirit and the bride say, Come. And let him that is athirst come. And whosoever will, let him take the water of life freely.', note: 'The final invitation of Scripture is open to whosoever will come.', theme: 'revelation' },
    { ref: 'Revelation 22:20', text: 'He which testifieth these things saith, Surely I come quickly. Amen. Even so, come, Lord Jesus.', note: 'The Bible closes with hope: Jesus is coming again.', theme: 'revelation' }
  ];

  /**
   * Picks a random verse, preferring ones not in `seenIds` when possible
   * so the same handful of verses don't repeat immediately. Falls back
   * to the full pool once everything has been seen.
   */
  function pickRandomVerse(seenIds) {
    seenIds = seenIds || [];
    const seenSet = new Set(seenIds);
    let pool = VERSES.map((v, i) => i).filter((i) => !seenSet.has(i));
    if (pool.length === 0) pool = VERSES.map((v, i) => i);
    const index = pool[Math.floor(Math.random() * pool.length)];
    return { index, verse: VERSES[index] };
  }

  global.Scripture = { VERSES, pickRandomVerse };
})(window);
